import {
  RiAddCircleLine,
  RiAmazonLine,
  RiAndroidFill,
  RiAndroidLine,
  RiAngularjsLine,
  RiAppleFill,
  RiAppleLine,
  RiArrowDownSLine,
  RiArrowLeftLine,
  RiArrowLeftSLine,
  RiArrowRightLine,
  RiArrowRightSLine,
  RiArrowRightUpLine,
  RiArrowUpLine,
  RiArtboardLine,
  RiArticleLine,
  RiAwardLine,
  RiBankCardLine,
  RiBarChartBoxLine,
  RiBarChartLine,
  RiBrainLine,
  RiBriefcase4Line,
  RiBuilding2Line,
  RiBuilding4Line,
  RiBuildingLine,
  RiCalendarEventLine,
  RiCalendarLine,
  RiCameraLensLine,
  RiChat3Line,
  RiChatVoiceLine,
  RiCheckLine,
  RiCheckboxCircleLine,
  RiCloseLine,
  RiCloudLine,
  RiCloudWindyLine,
  RiCodeLine,
  RiCodeSLine,
  RiCodeSSlashLine,
  RiCompass3Line,
  RiCss3Line,
  RiCupLine,
  RiCustomerService2Line,
  RiCustomerServiceLine,
  RiDashboard3Line,
  RiDatabase2Line,
  RiDatabaseLine,
  RiDiscussLine,
  RiDoubleQuotesL,
  RiEarthLine,
  RiErrorWarningLine,
  RiEyeLine,
  RiFacebookFill,
  RiFireLine,
  RiFlashlightLine,
  RiFlutterFill,
  RiFlutterLine,
  RiGithubFill,
  RiGithubLine,
  RiGlobalLine,
  RiGoogleLine,
  RiGroupLine,
  RiShakeHandsLine,
  RiHardDrive3Line,
  RiHeartLine,
  RiHome4Line,
  RiHospitalLine,
  RiInformationLine,
  RiInstagramFill,
  RiInstagramLine,
  RiStackLine,
  RiLayoutGridLine,
  RiLayoutMasonryLine,
  RiLeafLine,
  RiLightbulbFlashLine,
  RiLightbulbLine,
  RiLineChartLine,
  RiLink,
  RiLinkedinFill,
  RiLinkedinLine,
  RiLinksLine,
  RiLoader4Line,
  RiLockFill,
  RiLockLine,
  RiShieldKeyholeLine,
  RiLoopRightLine,
  RiMacbookLine,
  RiMailLine,
  RiMailSendLine,
  RiMapPinLine,
  RiMedalLine,
  RiMegaphoneLine,
  RiMessage3Line,
  RiMicrosoftLine,
  RiMoneyDollarCircleLine,
  RiMoneyPoundCircleLine,
  RiNodejsLine,
  RiOpenaiFill,
  RiPaletteLine,
  RiPauseLine,
  RiPencilRuler2Line,
  RiPencilRulerLine,
  RiPhoneLine,
  RiPieChartLine,
  RiPlantLine,
  RiPlayCircleLine,
  RiPlayLine,
  RiQuestionLine,
  RiReactjsLine,
  RiRecycleLine,
  RiRefreshLine,
  RiRobot2Line,
  RiRobotLine,
  RiSearchEyeLine,
  RiSearchLine,
  RiSendPlaneFill,
  RiSendPlaneLine,
  RiServerLine,
  RiSettings3Line,
  RiShareCircleLine,
  RiShareLine,
  RiShieldCheckFill,
  RiShieldCheckLine,
  RiShieldStarLine,
  RiShip2Line,
  RiShipLine,
  RiShoppingBag3Line,
  RiShoppingCart2Line,
  RiShoppingCartLine,
  RiSmartphoneLine,
  RiStarFill,
  RiStarLine,
  RiStore2Line,
  RiStore3Line,
  RiTeamLine,
  RiThumbDownLine,
  RiThumbUpLine,
  RiTimeLine,
  RiTimerFlashLine,
  RiToolsLine,
  RiTranslate2,
  RiTrophyLine,
  RiTwitterXFill,
  RiUploadCloud2Line,
  RiUserFollowLine,
  RiUserHeartLine,
  RiUserLine,
  RiUserLocationLine,
  RiVerifiedBadgeFill,
  RiVerifiedBadgeLine,
  RiVuejsLine,
  RiWhatsappFill,
  RiWordpressFill
} from 'react-icons/ri';

const iconMap = {
  'ri-add-circle-line': RiAddCircleLine,
  'ri-amazon-line': RiAmazonLine,
  'ri-android-fill': RiAndroidFill,
  'ri-android-line': RiAndroidLine,
  'ri-angularjs-line': RiAngularjsLine,
  'ri-apple-fill': RiAppleFill,
  'ri-apple-line': RiAppleLine,
  'ri-arrow-down-s-line': RiArrowDownSLine,
  'ri-arrow-left-line': RiArrowLeftLine,
  'ri-arrow-left-s-line': RiArrowLeftSLine,
  'ri-arrow-right-line': RiArrowRightLine,
  'ri-arrow-right-s-line': RiArrowRightSLine,
  'ri-arrow-right-up-line': RiArrowRightUpLine,
  'ri-arrow-up-line': RiArrowUpLine,
  'ri-artboard-line': RiArtboardLine,
  'ri-article-line': RiArticleLine,
  'ri-award-line': RiAwardLine,
  'ri-bank-card-line': RiBankCardLine,
  'ri-bar-chart-box-line': RiBarChartBoxLine,
  'ri-bar-chart-line': RiBarChartLine,
  'ri-brain-line': RiBrainLine,
  'ri-briefcase-4-line': RiBriefcase4Line,
  'ri-building-2-line': RiBuilding2Line,
  'ri-building-4-line': RiBuilding4Line,
  'ri-building-line': RiBuildingLine,
  'ri-calendar-event-line': RiCalendarEventLine,
  'ri-calendar-line': RiCalendarLine,
  'ri-camera-lens-line': RiCameraLensLine,
  'ri-chat-3-line': RiChat3Line,
  'ri-chat-voice-line': RiChatVoiceLine,
  'ri-check-line': RiCheckLine,
  'ri-checkbox-circle-line': RiCheckboxCircleLine,
  'ri-close-line': RiCloseLine,
  'ri-cloud-line': RiCloudLine,
  'ri-cloud-windy-line': RiCloudWindyLine,
  'ri-code-line': RiCodeLine,
  'ri-code-s-line': RiCodeSLine,
  'ri-code-s-slash-line': RiCodeSSlashLine,
  'ri-compass-3-line': RiCompass3Line,
  'ri-css3-line': RiCss3Line,
  'ri-cup-line': RiCupLine,
  'ri-customer-service-2-line': RiCustomerService2Line,
  'ri-customer-service-line': RiCustomerServiceLine,
  'ri-dashboard-3-line': RiDashboard3Line,
  'ri-database-2-line': RiDatabase2Line,
  'ri-database-line': RiDatabaseLine,
  'ri-discuss-line': RiDiscussLine,
  'ri-double-quotes-l': RiDoubleQuotesL,
  'ri-earth-line': RiEarthLine,
  'ri-error-warning-line': RiErrorWarningLine,
  'ri-eye-line': RiEyeLine,
  'ri-facebook-fill': RiFacebookFill,
  'ri-fire-line': RiFireLine,
  'ri-flashlight-line': RiFlashlightLine,
  'ri-flutter-fill': RiFlutterFill,
  'ri-flutter-line': RiFlutterLine,
  'ri-github-fill': RiGithubFill,
  'ri-github-line': RiGithubLine,
  'ri-global-line': RiGlobalLine,
  'ri-google-line': RiGoogleLine,
  'ri-group-line': RiGroupLine,
  'ri-shake-hands-line': RiShakeHandsLine,
  'ri-hard-drive-3-line': RiHardDrive3Line,
  'ri-heart-line': RiHeartLine,
  'ri-home-4-line': RiHome4Line,
  'ri-hospital-line': RiHospitalLine,
  'ri-information-line': RiInformationLine,
  'ri-instagram-fill': RiInstagramFill,
  'ri-instagram-line': RiInstagramLine,
  'ri-stack-line': RiStackLine,
  'ri-layout-grid-line': RiLayoutGridLine,
  'ri-layout-masonry-line': RiLayoutMasonryLine,
  'ri-leaf-line': RiLeafLine,
  'ri-lightbulb-flash-line': RiLightbulbFlashLine,
  'ri-lightbulb-line': RiLightbulbLine,
  'ri-line-chart-line': RiLineChartLine,
  'ri-link': RiLink,
  'ri-linkedin-fill': RiLinkedinFill,
  'ri-linkedin-line': RiLinkedinLine,
  'ri-links-line': RiLinksLine,
  'ri-loader-4-line': RiLoader4Line,
  'ri-lock-fill': RiLockFill,
  'ri-lock-line': RiLockLine,
  'ri-shield-keyhole-line': RiShieldKeyholeLine,
  'ri-loop-right-line': RiLoopRightLine,
  'ri-macbook-line': RiMacbookLine,
  'ri-mail-line': RiMailLine,
  'ri-mail-send-line': RiMailSendLine,
  'ri-map-pin-line': RiMapPinLine,
  'ri-medal-line': RiMedalLine,
  'ri-megaphone-line': RiMegaphoneLine,
  'ri-message-3-line': RiMessage3Line,
  'ri-microsoft-line': RiMicrosoftLine,
  'ri-money-dollar-circle-line': RiMoneyDollarCircleLine,
  'ri-money-pound-circle-line': RiMoneyPoundCircleLine,
  'ri-nodejs-line': RiNodejsLine,
  'ri-openai-fill': RiOpenaiFill,
  'ri-palette-line': RiPaletteLine,
  'ri-pause-line': RiPauseLine,
  'ri-pencil-ruler-2-line': RiPencilRuler2Line,
  'ri-pencil-ruler-line': RiPencilRulerLine,
  'ri-phone-line': RiPhoneLine,
  'ri-pie-chart-line': RiPieChartLine,
  'ri-plant-line': RiPlantLine,
  'ri-play-circle-line': RiPlayCircleLine,
  'ri-play-line': RiPlayLine,
  'ri-question-line': RiQuestionLine,
  'ri-reactjs-line': RiReactjsLine,
  'ri-recycle-line': RiRecycleLine,
  'ri-refresh-line': RiRefreshLine,
  'ri-robot-2-line': RiRobot2Line,
  'ri-robot-line': RiRobotLine,
  'ri-search-eye-line': RiSearchEyeLine,
  'ri-search-line': RiSearchLine,
  'ri-send-plane-fill': RiSendPlaneFill,
  'ri-send-plane-line': RiSendPlaneLine,
  'ri-server-line': RiServerLine,
  'ri-settings-3-line': RiSettings3Line,
  'ri-share-circle-line': RiShareCircleLine,
  'ri-share-line': RiShareLine,
  'ri-shield-check-fill': RiShieldCheckFill,
  'ri-shield-check-line': RiShieldCheckLine,
  'ri-shield-star-line': RiShieldStarLine,
  'ri-ship-2-line': RiShip2Line,
  'ri-ship-line': RiShipLine,
  'ri-shopping-bag-3-line': RiShoppingBag3Line,
  'ri-shopping-cart-2-line': RiShoppingCart2Line,
  'ri-shopping-cart-line': RiShoppingCartLine,
  'ri-smartphone-line': RiSmartphoneLine,
  'ri-star-fill': RiStarFill,
  'ri-star-line': RiStarLine,
  'ri-store-2-line': RiStore2Line,
  'ri-store-3-line': RiStore3Line,
  'ri-team-line': RiTeamLine,
  'ri-thumb-down-line': RiThumbDownLine,
  'ri-thumb-up-line': RiThumbUpLine,
  'ri-time-line': RiTimeLine,
  'ri-timer-flash-line': RiTimerFlashLine,
  'ri-tools-line': RiToolsLine,
  'ri-translate-2': RiTranslate2,
  'ri-trophy-line': RiTrophyLine,
  'ri-twitter-x-fill': RiTwitterXFill,
  'ri-upload-cloud-2-line': RiUploadCloud2Line,
  'ri-user-follow-line': RiUserFollowLine,
  'ri-user-heart-line': RiUserHeartLine,
  'ri-user-line': RiUserLine,
  'ri-user-location-line': RiUserLocationLine,
  'ri-verified-badge-fill': RiVerifiedBadgeFill,
  'ri-verified-badge-line': RiVerifiedBadgeLine,
  'ri-vuejs-line': RiVuejsLine,
  'ri-whatsapp-fill': RiWhatsappFill,
  'ri-wordpress-fill': RiWordpressFill
};

export default function Icon({ name, className = '', ...props }) {
  const IconComponent = iconMap[name];
  if (!IconComponent) {
    if (import.meta.env.DEV) {
      console.warn(`Icon: unknown icon name "${name}"`);
    }
    return null;
  }
  return <IconComponent className={className} {...props} />;
}

export { iconMap };
