// Industry data for NexCRM industry landing pages
// Each key maps to a URL slug: /nexcrm/industries/:slug

export const industryData = {
  general: {
    name: 'General Business',
    color: 'blue',
    icon: 'ri-building-line',
    hero: {
      badge: { text: 'All-Purpose CRM', icon: 'ri-building-line' },
      title: 'The CRM That Adapts to Any Business',
      subtitle: 'Whether you run a startup or a growing enterprise, NexCRM gives you the tools to manage leads, automate workflows, and close deals faster.',
    },
    stats: [
      { value: '10,000+', label: 'Businesses Served' },
      { value: '35%', label: 'Avg. Revenue Growth' },
      { value: '2.5x', label: 'Faster Deal Closure' },
      { value: '99.9%', label: 'Uptime Guaranteed' },
    ],
    services: [
      { icon: 'ri-contacts-book-line', title: 'Contact Management', desc: 'Centralized database for all your leads, customers, and vendors with smart tagging and segmentation.' },
      { icon: 'ri-funnel-line', title: 'Sales Pipeline', desc: 'Visual drag-and-drop pipeline to track every deal from first touch to closed-won.' },
      { icon: 'ri-mail-send-line', title: 'Email Campaigns', desc: 'Built-in email marketing with templates, scheduling, and open/click tracking.' },
      { icon: 'ri-bar-chart-box-line', title: 'Analytics Dashboard', desc: 'Real-time insights into sales performance, team productivity, and revenue forecasts.' },
      { icon: 'ri-robot-line', title: 'Workflow Automation', desc: 'Automate repetitive tasks — follow-ups, assignments, notifications — with zero coding.' },
      { icon: 'ri-customer-service-2-line', title: 'Support Ticketing', desc: 'Integrated helpdesk to manage customer issues with SLA tracking and escalation rules.' },
    ],
    whyChooseUs: [
      { icon: 'ri-plug-line', title: 'No-Code Setup', desc: 'Get started in minutes with guided onboarding — no developers needed.' },
      { icon: 'ri-shield-check-line', title: 'Enterprise Security', desc: 'SOC2-ready infrastructure with role-based access, audit logs, and encrypted data.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Affordable Pricing', desc: 'Plans starting at ₹999/mo — a fraction of the cost of Salesforce or HubSpot.' },
      { icon: 'ri-customer-service-line', title: 'Dedicated Support', desc: 'Real humans available via chat, email, and phone — no chatbot runaround.' },
    ],
    differentiators: [
      { title: 'Built for India', desc: 'GST invoicing, UPI payments, WhatsApp integration, and INR pricing — designed for Indian businesses from day one.' },
      { title: 'All-in-One Platform', desc: 'CRM, marketing, support, invoicing, and e-commerce in a single dashboard — no juggling 5 different tools.' },
      { title: 'White-Label Ready', desc: 'Rebrand the entire platform as your own — perfect for agencies and resellers.' },
      { title: 'Blazing Fast', desc: 'Sub-second page loads on Indian servers. No lag, no waiting, no frustration.' },
    ],
    modules: [
      { name: 'Lead Management', included: true },
      { name: 'Deal Pipeline', included: true },
      { name: 'Email Marketing', included: true },
      { name: 'WhatsApp Integration', included: true },
      { name: 'Invoicing & Payments', included: true },
      { name: 'Support Tickets', included: true },
      { name: 'Task Management', included: true },
      { name: 'Reports & Analytics', included: true },
      { name: 'Custom Fields', included: true },
      { name: 'API Access', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'NexCRM replaced three separate tools for us. Everything we need is in one place now.',
      author: 'Rahul Mehta',
      role: 'Founder',
      company: 'BrightPath Consulting',
    },
    faqs: [
      { q: 'Is NexCRM suitable for small businesses?', a: 'Absolutely. Our Starter plan is designed specifically for small teams with up to 500 leads and 2 team members.' },
      { q: 'Can I migrate from another CRM?', a: 'Yes. We offer free migration assistance for all paid plans, including data import from Zoho, HubSpot, and spreadsheets.' },
      { q: 'Is there a free trial?', a: 'Every plan comes with a 14-day free trial. No credit card required.' },
      { q: 'Do you offer custom integrations?', a: 'Yes. Our API supports REST endpoints for custom integrations, and our Enterprise plan includes dedicated integration support.' },
    ],
    seo: {
      title: 'NexCRM — All-Purpose CRM for Growing Businesses | NexSpire Solutions',
      description: 'Manage leads, automate sales, and grow revenue with NexCRM. Affordable CRM built for Indian businesses with WhatsApp, GST invoicing, and more.',
      keywords: 'CRM for small business India, affordable CRM software, lead management tool, sales automation CRM, WhatsApp CRM India, GST invoicing CRM, business CRM software, NexCRM',
    },
  },

  ecommerce: {
    name: 'E-Commerce',
    color: 'emerald',
    icon: 'ri-shopping-cart-2-line',
    hero: {
      badge: { text: 'E-Commerce CRM', icon: 'ri-shopping-cart-2-line' },
      title: 'Sell More. Retain Better. Grow Faster.',
      subtitle: 'Purpose-built CRM for online stores — manage orders, recover abandoned carts, segment customers, and drive repeat purchases.',
    },
    stats: [
      { value: '28%', label: 'Cart Recovery Rate' },
      { value: '3.2x', label: 'Repeat Purchase Rate' },
      { value: '₹2.4Cr', label: 'Revenue Recovered' },
      { value: '45%', label: 'Less Manual Work' },
    ],
    services: [
      { icon: 'ri-shopping-bag-line', title: 'Order Management', desc: 'Track orders from placement to delivery with automated status updates and customer notifications.' },
      { icon: 'ri-arrow-go-back-line', title: 'Cart Recovery', desc: 'Automated WhatsApp and email sequences to recover abandoned carts and boost conversions.' },
      { icon: 'ri-user-star-line', title: 'Customer Segmentation', desc: 'Segment by purchase history, order value, frequency, and behavior for targeted campaigns.' },
      { icon: 'ri-store-2-line', title: 'Product Catalog', desc: 'Manage your entire product catalog with variants, pricing, inventory tracking, and categories.' },
      { icon: 'ri-coupon-line', title: 'Promotions Engine', desc: 'Create discount codes, flash sales, BOGO offers, and loyalty rewards from one dashboard.' },
      { icon: 'ri-truck-line', title: 'Shipping Integration', desc: 'Connect with Shiprocket, Delhivery, and other carriers for automated shipping and tracking.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Commerce', desc: 'Accept orders, send catalogs, and recover carts directly on WhatsApp — where your customers already are.' },
      { icon: 'ri-line-chart-line', title: 'Revenue Analytics', desc: 'Track AOV, LTV, repeat rate, and cohort analysis to make data-driven growth decisions.' },
      { icon: 'ri-link', title: 'Multi-Channel Sync', desc: 'Sync inventory and orders across your website, marketplace listings, and social channels.' },
      { icon: 'ri-shield-check-line', title: 'PCI Compliant', desc: 'Secure payment processing with PCI-DSS compliance for Razorpay, Cashfree, and UPI.' },
    ],
    differentiators: [
      { title: 'Built for D2C Brands', desc: 'Unlike generic CRMs, every feature is designed for online sellers — from cart recovery to cohort analysis.' },
      { title: 'WhatsApp-First', desc: 'Native WhatsApp Business API integration for order updates, cart recovery, and customer support.' },
      { title: 'Indian Payment Stack', desc: 'Razorpay, Cashfree, Paytm, UPI — all integrated natively with automatic reconciliation.' },
      { title: 'No Per-Order Fees', desc: 'Flat monthly pricing regardless of order volume. Scale without worrying about transaction fees.' },
    ],
    modules: [
      { name: 'Product Catalog', included: true },
      { name: 'Order Management', included: true },
      { name: 'Cart Recovery', included: true },
      { name: 'Customer Segmentation', included: true },
      { name: 'Discount & Coupons', included: true },
      { name: 'Shipping Integration', included: true },
      { name: 'Payment Gateway', included: true },
      { name: 'Inventory Management', included: true },
      { name: 'Reviews & Ratings', included: true },
      { name: 'WhatsApp Commerce', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Our cart recovery rate jumped from 8% to 28% within the first month. The WhatsApp integration is a game-changer.',
      author: 'Priya Sharma',
      role: 'Co-founder',
      company: 'UrbanKraft D2C',
    },
    faqs: [
      { q: 'Does NexCRM integrate with Shopify?', a: 'Yes. We offer native Shopify integration that syncs products, orders, and customers in real-time.' },
      { q: 'Can I manage multiple stores?', a: 'Yes. Our Business and Enterprise plans support multi-store management from a single dashboard.' },
      { q: 'How does cart recovery work?', a: 'When a customer abandons their cart, NexCRM automatically sends a sequence of WhatsApp messages and emails with personalized product reminders.' },
      { q: 'Do you charge per order?', a: 'No. All plans have flat monthly pricing regardless of your order volume.' },
    ],
    seo: {
      title: 'E-Commerce CRM — Boost Sales & Recover Carts | NexCRM',
      description: 'CRM built for online stores. Recover abandoned carts, segment customers, and drive repeat purchases with WhatsApp commerce and automation.',
      keywords: 'ecommerce CRM India, abandoned cart recovery, online store CRM, Shopify CRM alternative, WhatsApp commerce, customer retention ecommerce, order management CRM',
    },
  },

  realestate: {
    name: 'Real Estate',
    color: 'amber',
    icon: 'ri-home-smile-line',
    hero: {
      badge: { text: 'Real Estate CRM', icon: 'ri-home-smile-line' },
      title: 'Close More Deals. Manage Every Property.',
      subtitle: 'From lead capture to possession handover — manage your entire real estate business with a CRM built for brokers, developers, and agencies.',
    },
    stats: [
      { value: '40%', label: 'Faster Lead Response' },
      { value: '2x', label: 'More Site Visits' },
      { value: '₹50Cr+', label: 'Deals Closed on Platform' },
      { value: '60%', label: 'Less Follow-up Effort' },
    ],
    services: [
      { icon: 'ri-user-add-line', title: 'Lead Capture', desc: 'Auto-capture leads from 99acres, MagicBricks, Facebook Ads, website forms, and walk-ins.' },
      { icon: 'ri-building-2-line', title: 'Property Listings', desc: 'Manage your complete property inventory with photos, floor plans, pricing, and availability status.' },
      { icon: 'ri-calendar-check-line', title: 'Site Visit Scheduling', desc: 'Automated site visit booking with calendar sync, reminders, and follow-up sequences.' },
      { icon: 'ri-file-list-3-line', title: 'Document Management', desc: 'Store and share agreements, brochures, and legal documents with role-based access control.' },
      { icon: 'ri-team-line', title: 'Broker Management', desc: 'Track channel partner performance, commission structures, and referral pipelines.' },
      { icon: 'ri-map-pin-line', title: 'Location Intelligence', desc: 'Map-based property search with proximity filters, locality trends, and price heatmaps.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Follow-ups', desc: 'Automated property alerts and follow-ups via WhatsApp — the channel buyers actually respond on.' },
      { icon: 'ri-smartphone-line', title: 'Mobile-First CRM', desc: 'Your sales team closes deals on the field. Our mobile app gives them everything they need on-the-go.' },
      { icon: 'ri-pie-chart-line', title: 'Inventory Analytics', desc: 'Real-time dashboards showing available units, pricing trends, and inventory turnover by project.' },
      { icon: 'ri-shield-user-line', title: 'RERA Compliant', desc: 'Built-in compliance features for RERA documentation, project registration tracking, and buyer agreements.' },
    ],
    differentiators: [
      { title: 'Portal Integration', desc: '99acres, MagicBricks, Housing.com — leads flow directly into your pipeline without manual entry.' },
      { title: 'Built for Indian Real Estate', desc: 'RERA compliance, stamp duty calculators, GST handling, and INR pricing — not a generic Western CRM.' },
      { title: 'Channel Partner Portal', desc: 'Give brokers their own login to submit leads, track commissions, and access marketing collateral.' },
      { title: 'Demand-Supply Matching', desc: 'AI-powered matching engine that connects buyer requirements to available inventory automatically.' },
    ],
    modules: [
      { name: 'Lead Management', included: true },
      { name: 'Property Listings', included: true },
      { name: 'Site Visit Scheduling', included: true },
      { name: 'Broker Portal', included: true },
      { name: 'Document Management', included: true },
      { name: 'Payment Tracking', included: true },
      { name: 'WhatsApp Integration', included: true },
      { name: 'Inventory Dashboard', included: true },
      { name: 'Commission Calculator', included: true },
      { name: 'RERA Compliance', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'We went from losing leads in spreadsheets to closing 40% more site visits. The portal integrations alone saved us 3 hours daily.',
      author: 'Vikram Desai',
      role: 'Director',
      company: 'Horizon Realty Group',
    },
    faqs: [
      { q: 'Can I import leads from property portals?', a: 'Yes. NexCRM integrates with 99acres, MagicBricks, Housing.com, and Facebook Lead Ads for automatic lead import.' },
      { q: 'Is it suitable for builders and developers?', a: 'Absolutely. Our platform supports multi-project management with inventory tracking, construction updates, and buyer communication.' },
      { q: 'Can channel partners access the system?', a: 'Yes. You can create broker accounts with limited access to submit leads, view commissions, and download marketing materials.' },
      { q: 'How does the commission tracking work?', a: 'Define commission structures per project or broker, and NexCRM automatically calculates payable amounts when deals close.' },
    ],
    seo: {
      title: 'Real Estate CRM — Manage Properties, Leads & Brokers | NexCRM',
      description: 'CRM for real estate brokers and developers. Capture leads from portals, schedule site visits, manage inventory, and close more deals.',
      keywords: 'real estate CRM India, property management CRM, broker CRM software, 99acres integration CRM, real estate lead management, site visit scheduler, builder CRM',
    },
  },

  services: {
    name: 'Professional Services',
    color: 'indigo',
    icon: 'ri-briefcase-line',
    hero: {
      badge: { text: 'Services CRM', icon: 'ri-briefcase-line' },
      title: 'Win More Clients. Deliver Exceptional Service.',
      subtitle: 'CRM designed for consultants, agencies, and service professionals — manage proposals, projects, and client relationships in one place.',
    },
    stats: [
      { value: '50%', label: 'Faster Proposals' },
      { value: '3x', label: 'Client Retention' },
      { value: '₹8Cr+', label: 'Projects Managed' },
      { value: '70%', label: 'Less Admin Work' },
    ],
    services: [
      { icon: 'ri-file-text-line', title: 'Proposal Builder', desc: 'Create professional proposals with templates, pricing tables, and e-signatures in minutes.' },
      { icon: 'ri-calendar-todo-line', title: 'Project Tracking', desc: 'Track project milestones, deliverables, timelines, and team workload from a single dashboard.' },
      { icon: 'ri-time-line', title: 'Time Tracking', desc: 'Log billable hours by project, client, or task — then auto-generate invoices from time entries.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Invoicing', desc: 'GST-compliant invoicing with recurring billing, payment reminders, and online payment collection.' },
      { icon: 'ri-contacts-book-line', title: 'Client Portal', desc: 'Give clients a branded portal to view project progress, approve deliverables, and download invoices.' },
      { icon: 'ri-bar-chart-grouped-line', title: 'Resource Planning', desc: 'Allocate team members across projects with capacity planning and utilization tracking.' },
    ],
    whyChooseUs: [
      { icon: 'ri-draft-line', title: 'Proposal to Invoice', desc: 'Seamless flow from proposal → approval → project → invoice — no re-entering data.' },
      { icon: 'ri-team-line', title: 'Team Collaboration', desc: 'Internal notes, task assignments, file sharing, and @mentions keep everyone aligned.' },
      { icon: 'ri-line-chart-line', title: 'Profitability Insights', desc: 'See revenue, costs, and margins per project, client, or service line in real-time.' },
      { icon: 'ri-repeat-line', title: 'Recurring Revenue', desc: 'Manage retainer clients with recurring invoices, auto-renewals, and contract tracking.' },
    ],
    differentiators: [
      { title: 'Built for Billable Teams', desc: 'Time tracking, utilization reports, and project margins — not features bolted onto a sales CRM.' },
      { title: 'Client-Facing Portal', desc: 'Give clients transparency without giving them admin access. Branded portals build trust.' },
      { title: 'GST-Ready Invoicing', desc: 'CGST, SGST, IGST, HSN codes, e-invoicing — compliant with Indian tax requirements out of the box.' },
      { title: 'Scope Creep Alerts', desc: 'Track hours against estimates. Get alerted when a project is heading over budget before it is too late.' },
    ],
    modules: [
      { name: 'Lead & Opportunity Management', included: true },
      { name: 'Proposal Builder', included: true },
      { name: 'Project Management', included: true },
      { name: 'Time Tracking', included: true },
      { name: 'Invoicing & Payments', included: true },
      { name: 'Client Portal', included: true },
      { name: 'Resource Planning', included: true },
      { name: 'Contract Management', included: true },
      { name: 'Expense Tracking', included: true },
      { name: 'Reports & Dashboards', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'We cut our proposal-to-close time by half. The client portal alone has reduced back-and-forth emails by 80%.',
      author: 'Ankit Jain',
      role: 'Managing Partner',
      company: 'Stride Digital Agency',
    },
    faqs: [
      { q: 'Is NexCRM suitable for freelancers?', a: 'Yes. Our Starter plan is perfect for freelancers with features like time tracking, invoicing, and client management.' },
      { q: 'Can I track profitability per project?', a: 'Absolutely. NexCRM tracks revenue, time costs, and expenses per project to give you real-time margin visibility.' },
      { q: 'Does it support retainer billing?', a: 'Yes. Set up recurring invoices with auto-generation, payment reminders, and contract renewal alerts.' },
      { q: 'Can clients see project progress?', a: 'Yes. The client portal lets clients view milestones, approve deliverables, download invoices, and communicate with your team.' },
    ],
    seo: {
      title: 'Professional Services CRM — Proposals, Projects & Invoicing | NexCRM',
      description: 'CRM for consultants, agencies, and service businesses. Manage proposals, track projects, bill clients, and grow your service business.',
      keywords: 'services CRM India, consulting CRM, agency CRM software, project management CRM, proposal management tool, client billing CRM, freelancer CRM',
    },
  },

  education: {
    name: 'Education',
    color: 'violet',
    icon: 'ri-graduation-cap-line',
    hero: {
      badge: { text: 'Education CRM', icon: 'ri-graduation-cap-line' },
      title: 'Enroll More Students. Engage Every Learner.',
      subtitle: 'From inquiry to enrollment to alumni — manage the complete student lifecycle with a CRM built for schools, colleges, and edtech platforms.',
    },
    stats: [
      { value: '45%', label: 'Higher Enrollment' },
      { value: '3x', label: 'Faster Inquiry Response' },
      { value: '10,000+', label: 'Students Managed' },
      { value: '60%', label: 'Less Manual Follow-up' },
    ],
    services: [
      { icon: 'ri-user-add-line', title: 'Inquiry Management', desc: 'Capture inquiries from website, social media, walk-ins, and referrals with automatic assignment to counselors.' },
      { icon: 'ri-road-map-line', title: 'Enrollment Pipeline', desc: 'Visual pipeline from inquiry → application → interview → offer → enrolled with stage-wise automation.' },
      { icon: 'ri-parent-line', title: 'Parent Communication', desc: 'Automated updates to parents via WhatsApp and email — fee reminders, progress reports, and event notifications.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Fee Management', desc: 'Track fee payments, generate receipts, send reminders, and manage installment plans with ease.' },
      { icon: 'ri-calendar-event-line', title: 'Event Management', desc: 'Schedule open houses, campus tours, webinars, and orientations with RSVP tracking.' },
      { icon: 'ri-file-chart-line', title: 'Performance Analytics', desc: 'Track counselor productivity, source effectiveness, conversion rates, and enrollment trends.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Engagement', desc: 'Reach students and parents on WhatsApp — the channel they actually read and respond to.' },
      { icon: 'ri-flow-chart', title: 'Enrollment Automation', desc: 'Auto-assign leads, trigger follow-up sequences, and move students through stages without manual intervention.' },
      { icon: 'ri-group-line', title: 'Multi-Campus Support', desc: 'Manage multiple branches or campuses from a single dashboard with campus-wise reporting.' },
      { icon: 'ri-lock-line', title: 'Data Privacy', desc: 'Student data encrypted at rest and in transit. Role-based access ensures only authorized staff see sensitive information.' },
    ],
    differentiators: [
      { title: 'Student Lifecycle CRM', desc: 'Not just admissions — manage the full journey from first inquiry to alumni engagement and placement tracking.' },
      { title: 'Counselor Performance', desc: 'Track individual counselor metrics — call volume, conversion rate, follow-up compliance — to optimize your team.' },
      { title: 'Source Attribution', desc: 'Know exactly which campaigns, portals, and referrers drive enrollments — down to the cost per admission.' },
      { title: 'Batch & Course Management', desc: 'Organize students by batch, course, and semester with automated communications for each segment.' },
    ],
    modules: [
      { name: 'Inquiry Capture', included: true },
      { name: 'Enrollment Pipeline', included: true },
      { name: 'Fee Management', included: true },
      { name: 'Parent Portal', included: true },
      { name: 'WhatsApp Communication', included: true },
      { name: 'Counselor Dashboard', included: true },
      { name: 'Event Management', included: true },
      { name: 'Document Collection', included: true },
      { name: 'Alumni Tracking', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Our enrollment rate increased by 45% after switching to NexCRM. The automated follow-ups ensure no inquiry falls through the cracks.',
      author: 'Dr. Meena Krishnan',
      role: 'Director of Admissions',
      company: 'Vidya International School',
    },
    faqs: [
      { q: 'Is this suitable for coaching institutes?', a: 'Yes. NexCRM works for schools, colleges, coaching centers, and edtech platforms. The enrollment pipeline adapts to any admission process.' },
      { q: 'Can parents access the system?', a: 'Parents receive automated updates via WhatsApp and email. A dedicated parent portal is available on Business and Enterprise plans.' },
      { q: 'How does fee tracking work?', a: 'Create fee structures with installment plans, auto-generate invoices, send payment reminders, and track collections in real-time.' },
      { q: 'Can I manage multiple branches?', a: 'Yes. Multi-campus support is available on Business and Enterprise plans with branch-wise data isolation and consolidated reporting.' },
    ],
    seo: {
      title: 'Education CRM — Enrollment, Fees & Student Management | NexCRM',
      description: 'CRM for schools, colleges, and edtech. Manage inquiries, automate enrollment, track fees, and engage students and parents.',
      keywords: 'education CRM India, school admission CRM, student management software, edtech CRM, enrollment automation, fee management system, coaching institute CRM',
    },
  },

  healthcare: {
    name: 'Healthcare',
    color: 'rose',
    icon: 'ri-heart-pulse-line',
    hero: {
      badge: { text: 'Healthcare CRM', icon: 'ri-heart-pulse-line' },
      title: 'Better Patient Relationships. Better Outcomes.',
      subtitle: 'CRM for hospitals, clinics, and wellness centers — manage patient journeys, appointments, and communications with care.',
    },
    stats: [
      { value: '35%', label: 'Fewer No-Shows' },
      { value: '2x', label: 'Patient Retention' },
      { value: '50,000+', label: 'Appointments Managed' },
      { value: '40%', label: 'Less Admin Time' },
    ],
    services: [
      { icon: 'ri-calendar-check-line', title: 'Appointment Scheduling', desc: 'Online booking with doctor availability, slot management, and automated confirmation and reminder messages.' },
      { icon: 'ri-user-heart-line', title: 'Patient Records', desc: 'Centralized patient profiles with visit history, prescriptions, reports, and communication logs.' },
      { icon: 'ri-whatsapp-line', title: 'Patient Communication', desc: 'Automated appointment reminders, follow-up messages, and health tips via WhatsApp and SMS.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Billing & Insurance', desc: 'Generate bills, track insurance claims, manage payment plans, and send automated payment reminders.' },
      { icon: 'ri-stethoscope-line', title: 'Doctor Dashboard', desc: 'Each doctor gets a personalized dashboard with their schedule, patient queue, and performance metrics.' },
      { icon: 'ri-feedback-line', title: 'Patient Feedback', desc: 'Automated post-visit surveys to track patient satisfaction and identify improvement areas.' },
    ],
    whyChooseUs: [
      { icon: 'ri-shield-check-line', title: 'HIPAA-Aware Security', desc: 'Encrypted data storage, role-based access, audit trails, and consent management for patient privacy.' },
      { icon: 'ri-smartphone-line', title: 'Patient App', desc: 'Patients can book appointments, view reports, and message their doctor from a branded mobile experience.' },
      { icon: 'ri-bar-chart-box-line', title: 'Operational Insights', desc: 'Track patient flow, revenue per department, doctor utilization, and appointment trends in real-time.' },
      { icon: 'ri-heart-line', title: 'Care Coordination', desc: 'Multi-doctor referrals, treatment plans, and follow-up protocols managed within the patient record.' },
    ],
    differentiators: [
      { title: 'Patient-Centric Design', desc: 'Every feature revolves around the patient journey — not retrofitted sales funnels labeled as healthcare CRM.' },
      { title: 'WhatsApp Reminders', desc: 'Reduce no-shows by 35% with automated appointment reminders and pre-visit instructions on WhatsApp.' },
      { title: 'Multi-Location Support', desc: 'Manage multiple clinics or hospital branches with location-wise scheduling, billing, and reporting.' },
      { title: 'Indian Healthcare Stack', desc: 'ABHA integration, CGHS/ECHS support, GST-compliant billing, and UPI payment collection built in.' },
    ],
    modules: [
      { name: 'Appointment Scheduling', included: true },
      { name: 'Patient Records', included: true },
      { name: 'Doctor Dashboard', included: true },
      { name: 'Billing & Payments', included: true },
      { name: 'WhatsApp Reminders', included: true },
      { name: 'Patient Feedback', included: true },
      { name: 'Insurance Claims', included: true },
      { name: 'Referral Management', included: true },
      { name: 'Pharmacy Integration', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Patient no-shows dropped by 35% in the first month. The WhatsApp reminders and online booking changed how our clinic operates.',
      author: 'Dr. Suresh Patel',
      role: 'Chief Medical Officer',
      company: 'LifeCare Clinics',
    },
    faqs: [
      { q: 'Is patient data secure?', a: 'Yes. All data is encrypted at rest and in transit. We implement role-based access, audit logs, and consent management for patient privacy.' },
      { q: 'Can patients book appointments online?', a: 'Yes. Patients can book via a branded booking page, WhatsApp, or your website with real-time doctor availability.' },
      { q: 'Does it support multiple doctors?', a: 'Absolutely. Each doctor gets their own schedule, patient list, and performance dashboard within the shared clinic account.' },
      { q: 'Can I integrate with lab systems?', a: 'Yes. Our API supports integration with lab information systems to auto-import reports into patient records.' },
    ],
    seo: {
      title: 'Healthcare CRM — Patient Management & Appointments | NexCRM',
      description: 'CRM for hospitals and clinics. Manage appointments, patient records, billing, and communications. Reduce no-shows with WhatsApp reminders.',
      keywords: 'healthcare CRM India, hospital CRM software, patient management system, clinic appointment software, doctor CRM, medical practice management, WhatsApp reminders healthcare',
    },
  },

  hospitality: {
    name: 'Hospitality',
    color: 'orange',
    icon: 'ri-hotel-line',
    hero: {
      badge: { text: 'Hospitality CRM', icon: 'ri-hotel-line' },
      title: 'Delight Every Guest. Fill Every Room.',
      subtitle: 'CRM for hotels, resorts, and vacation rentals — manage bookings, guest preferences, and loyalty programs to maximize occupancy and revenue.',
    },
    stats: [
      { value: '25%', label: 'Higher Occupancy' },
      { value: '4.8★', label: 'Avg Guest Rating' },
      { value: '₹12Cr+', label: 'Bookings Managed' },
      { value: '3x', label: 'Repeat Guest Rate' },
    ],
    services: [
      { icon: 'ri-calendar-check-line', title: 'Booking Management', desc: 'Centralized calendar for room bookings, check-ins, check-outs, and housekeeping coordination.' },
      { icon: 'ri-user-star-line', title: 'Guest Profiles', desc: 'Track guest preferences, dietary requirements, past stays, and feedback for personalized experiences.' },
      { icon: 'ri-gift-line', title: 'Loyalty Program', desc: 'Points-based loyalty system with tiered rewards, birthday offers, and referral bonuses.' },
      { icon: 'ri-restaurant-line', title: 'F&B Management', desc: 'Restaurant and banquet bookings, menu management, and F&B revenue tracking.' },
      { icon: 'ri-star-line', title: 'Review Management', desc: 'Monitor and respond to reviews on Google, TripAdvisor, and OTAs from a single dashboard.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Revenue Management', desc: 'Dynamic pricing suggestions based on occupancy, season, demand patterns, and competitor rates.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Concierge', desc: 'Pre-arrival messages, in-stay requests, and post-checkout feedback — all automated on WhatsApp.' },
      { icon: 'ri-global-line', title: 'OTA Integration', desc: 'Sync availability and rates with Booking.com, MakeMyTrip, Goibibo, and other OTAs in real-time.' },
      { icon: 'ri-bar-chart-box-line', title: 'RevPAR Analytics', desc: 'Track RevPAR, ADR, occupancy trends, and channel-wise booking performance with actionable dashboards.' },
      { icon: 'ri-group-line', title: 'Event & Banquet CRM', desc: 'Manage corporate events, weddings, and conferences with dedicated booking and coordination workflows.' },
    ],
    differentiators: [
      { title: 'Guest Memory', desc: 'Remember every guest preference across stays — room type, pillow choice, dietary needs — for truly personalized hospitality.' },
      { title: 'Channel Manager Built In', desc: 'No third-party channel manager needed. Sync rates and availability across all OTAs directly from NexCRM.' },
      { title: 'Indian Hospitality Focus', desc: 'GST invoicing, FSSAI compliance tracking, UPI payments, and support for Indian OTAs like MakeMyTrip and Goibibo.' },
      { title: 'Seasonal Automation', desc: 'Pre-configured workflows for peak seasons, festivals, and off-season promotions to maximize year-round revenue.' },
    ],
    modules: [
      { name: 'Booking Calendar', included: true },
      { name: 'Guest Profiles', included: true },
      { name: 'Loyalty Program', included: true },
      { name: 'F&B Management', included: true },
      { name: 'Review Monitoring', included: true },
      { name: 'Revenue Management', included: true },
      { name: 'Housekeeping Tracker', included: true },
      { name: 'OTA Sync', included: true },
      { name: 'WhatsApp Concierge', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Our repeat guest rate tripled after implementing the loyalty program and personalized WhatsApp communications.',
      author: 'Aisha Khan',
      role: 'General Manager',
      company: 'Seaside Heritage Resort',
    },
    faqs: [
      { q: 'Does it integrate with booking platforms?', a: 'Yes. NexCRM syncs with Booking.com, MakeMyTrip, Goibibo, Airbnb, and other OTAs for unified availability and rate management.' },
      { q: 'Can I manage multiple properties?', a: 'Yes. Business and Enterprise plans support multi-property management with property-wise dashboards and consolidated reporting.' },
      { q: 'How does the loyalty program work?', a: 'Guests earn points per stay that can be redeemed for discounts, upgrades, or freebies. You define the tiers, rewards, and earning rules.' },
      { q: 'Is it suitable for restaurants too?', a: 'For standalone restaurants, we recommend the Restaurant industry CRM. The hospitality module covers F&B within hotels and resorts.' },
    ],
    seo: {
      title: 'Hospitality CRM — Hotel & Resort Guest Management | NexCRM',
      description: 'CRM for hotels and resorts. Manage bookings, guest preferences, loyalty programs, and OTA channels. Maximize occupancy and guest satisfaction.',
      keywords: 'hotel CRM India, hospitality CRM software, guest management system, resort booking CRM, OTA management, hotel loyalty program, guest experience platform',
    },
  },

  travel: {
    name: 'Travel & Tourism',
    color: 'cyan',
    icon: 'ri-flight-takeoff-line',
    hero: {
      badge: { text: 'Travel CRM', icon: 'ri-flight-takeoff-line' },
      title: 'Book More Trips. Build Lifelong Travelers.',
      subtitle: 'CRM for travel agencies, tour operators, and DMCs — manage itineraries, bookings, and traveler relationships from inquiry to post-trip feedback.',
    },
    stats: [
      { value: '55%', label: 'Faster Quote Turnaround' },
      { value: '2.8x', label: 'Repeat Booking Rate' },
      { value: '₹20Cr+', label: 'Bookings Processed' },
      { value: '40%', label: 'Less Follow-up Effort' },
    ],
    services: [
      { icon: 'ri-route-line', title: 'Itinerary Builder', desc: 'Drag-and-drop itinerary creator with day-wise planning, accommodation, transfers, and activities.' },
      { icon: 'ri-file-text-line', title: 'Quote Management', desc: 'Generate branded quotes with package details, pricing breakdowns, and terms — send via WhatsApp or email.' },
      { icon: 'ri-group-line', title: 'Group Bookings', desc: 'Manage group tours with participant lists, rooming assignments, and bulk communication.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Payment Tracking', desc: 'Track deposits, installments, and final payments with automated reminders and receipt generation.' },
      { icon: 'ri-hotel-line', title: 'Supplier Management', desc: 'Maintain a database of hotels, airlines, transport providers, and activity partners with rate cards.' },
      { icon: 'ri-star-line', title: 'Post-Trip Engagement', desc: 'Automated feedback surveys, photo sharing, and re-engagement campaigns for repeat bookings.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Itineraries', desc: 'Share itineraries and booking confirmations directly on WhatsApp — no more lost emails.' },
      { icon: 'ri-currency-line', title: 'Multi-Currency', desc: 'Quote in any currency, track payments in INR, and handle forex with automatic rate conversion.' },
      { icon: 'ri-line-chart-line', title: 'Revenue Analytics', desc: 'Track revenue by destination, package type, agent, and season to optimize your offerings.' },
      { icon: 'ri-smartphone-line', title: 'Traveler App', desc: 'Travelers get a branded app with their itinerary, documents, emergency contacts, and real-time updates.' },
    ],
    differentiators: [
      { title: 'Built for Indian Travel Trade', desc: 'B2B agent management, LTC/LTA tracking, forex compliance, and GST-TCS handling built in.' },
      { title: 'Itinerary as Marketing', desc: 'Beautiful, shareable itineraries that double as marketing material — travelers share them, bringing you referrals.' },
      { title: 'Supplier Rate Engine', desc: 'Maintain seasonal rate cards from suppliers, auto-calculate package costs, and protect your margins.' },
      { title: 'Agent & B2B Portal', desc: 'Give sub-agents their own portal to search packages, create bookings, and track commissions.' },
    ],
    modules: [
      { name: 'Lead Management', included: true },
      { name: 'Itinerary Builder', included: true },
      { name: 'Quote Generator', included: true },
      { name: 'Booking Management', included: true },
      { name: 'Payment Tracking', included: true },
      { name: 'Supplier Database', included: true },
      { name: 'WhatsApp Integration', included: true },
      { name: 'Group Tour Manager', included: true },
      { name: 'Agent Portal', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'Quote turnaround went from 2 days to 4 hours. Our conversion rate doubled because we respond faster than anyone else.',
      author: 'Deepak Nair',
      role: 'Founder',
      company: 'Wanderlust Holidays',
    },
    faqs: [
      { q: 'Can I manage both B2C and B2B bookings?', a: 'Yes. NexCRM supports direct customer bookings and a B2B agent portal with separate pricing, commissions, and access controls.' },
      { q: 'Does it handle international packages?', a: 'Absolutely. Multi-currency quoting, forex tracking, visa document collection, and international supplier management are all included.' },
      { q: 'How does the itinerary builder work?', a: 'Drag-and-drop interface where you add days, accommodation, transfers, activities, and meals. Generate a branded PDF or shareable link instantly.' },
      { q: 'Can I track supplier payments?', a: 'Yes. Track what you owe suppliers, reconcile against what clients paid, and see your margins per booking in real-time.' },
    ],
    seo: {
      title: 'Travel CRM — Itineraries, Bookings & Agent Management | NexCRM',
      description: 'CRM for travel agencies and tour operators. Build itineraries, manage bookings, track payments, and grow your travel business.',
      keywords: 'travel agency CRM India, tour operator CRM, itinerary builder, travel booking management, travel agent software, holiday package CRM, tourism CRM',
    },
  },

  fitness: {
    name: 'Fitness & Gym',
    color: 'red',
    icon: 'ri-boxing-line',
    hero: {
      badge: { text: 'Fitness CRM', icon: 'ri-boxing-line' },
      title: 'Grow Your Gym. Retain Every Member.',
      subtitle: 'CRM for gyms, yoga studios, and fitness centers — manage memberships, class schedules, trainer assignments, and member engagement.',
    },
    stats: [
      { value: '30%', label: 'Less Member Churn' },
      { value: '2x', label: 'Referral Sign-ups' },
      { value: '5,000+', label: 'Members Managed' },
      { value: '50%', label: 'Less Admin Work' },
    ],
    services: [
      { icon: 'ri-vip-crown-line', title: 'Membership Management', desc: 'Manage membership plans, renewals, freezes, upgrades, and cancellations with automated billing.' },
      { icon: 'ri-calendar-line', title: 'Class Scheduling', desc: 'Schedule group classes, personal training sessions, and workshops with capacity limits and waitlists.' },
      { icon: 'ri-user-settings-line', title: 'Trainer Management', desc: 'Assign trainers to members, track session logs, and manage trainer schedules and payroll.' },
      { icon: 'ri-heart-pulse-line', title: 'Member Progress', desc: 'Track body measurements, workout plans, fitness goals, and progress photos for each member.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Payment Collection', desc: 'Automated fee collection with UPI, card payments, and cash tracking. Send renewal reminders before expiry.' },
      { icon: 'ri-door-open-line', title: 'Check-in System', desc: 'QR code or biometric check-in tracking with attendance reports and peak hour analytics.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Engagement', desc: 'Workout reminders, class schedules, renewal alerts, and motivational messages delivered via WhatsApp.' },
      { icon: 'ri-line-chart-line', title: 'Retention Analytics', desc: 'Identify at-risk members based on attendance patterns and trigger automated re-engagement campaigns.' },
      { icon: 'ri-smartphone-line', title: 'Member App', desc: 'Branded mobile app for members to book classes, track progress, and manage their membership.' },
      { icon: 'ri-gift-line', title: 'Referral Program', desc: 'Built-in referral system with rewards tracking to turn your best members into brand ambassadors.' },
    ],
    differentiators: [
      { title: 'Attendance Intelligence', desc: 'AI identifies members likely to churn based on declining attendance and triggers retention workflows automatically.' },
      { title: 'Trainer Performance', desc: 'Track trainer ratings, session completion rates, and member satisfaction to reward your best coaches.' },
      { title: 'Indian Payment Stack', desc: 'Razorpay, UPI auto-debit, and cash tracking — handle the reality of how Indian gym members actually pay.' },
      { title: 'Multi-Branch Support', desc: 'Manage multiple gym locations with cross-branch membership, consolidated reporting, and branch-wise P&L.' },
    ],
    modules: [
      { name: 'Membership Plans', included: true },
      { name: 'Class Scheduling', included: true },
      { name: 'Trainer Assignment', included: true },
      { name: 'Check-in Tracking', included: true },
      { name: 'Payment Collection', included: true },
      { name: 'Member Progress', included: true },
      { name: 'Referral Program', included: true },
      { name: 'WhatsApp Reminders', included: true },
      { name: 'Attendance Reports', included: true },
      { name: 'Lead Management', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'Member retention improved by 30% within 3 months. The automated WhatsApp reminders keep members accountable and engaged.',
      author: 'Ravi Kumar',
      role: 'Owner',
      company: 'IronFit Gym Chain',
    },
    faqs: [
      { q: 'Can members book classes online?', a: 'Yes. Members can book group classes and PT sessions from the member app or a branded booking page with real-time availability.' },
      { q: 'Does it handle membership freezes?', a: 'Yes. Members can request freezes, and the system automatically extends their membership end date by the frozen period.' },
      { q: 'Can I track trainer commissions?', a: 'Absolutely. Set per-session or percentage-based commission structures and auto-calculate monthly payouts.' },
      { q: 'How does the check-in system work?', a: 'Members check in via QR code on their phone or biometric integration. Attendance is tracked automatically with reports on peak hours.' },
    ],
    seo: {
      title: 'Fitness CRM — Gym Membership & Class Management | NexCRM',
      description: 'CRM for gyms and fitness centers. Manage memberships, schedules, trainer assignments, and member engagement. Reduce churn with smart automation.',
      keywords: 'gym CRM India, fitness center CRM, gym management software, membership management system, personal trainer CRM, gym billing software, fitness studio CRM',
    },
  },

  legal: {
    name: 'Legal',
    color: 'slate',
    icon: 'ri-scales-3-line',
    hero: {
      badge: { text: 'Legal CRM', icon: 'ri-scales-3-line' },
      title: 'Manage Cases. Serve Clients. Grow Your Practice.',
      subtitle: 'CRM for law firms, legal consultants, and corporate legal teams — manage cases, deadlines, documents, and client communications efficiently.',
    },
    stats: [
      { value: '40%', label: 'Less Missed Deadlines' },
      { value: '2x', label: 'Client Intake Speed' },
      { value: '₹5Cr+', label: 'Billings Tracked' },
      { value: '60%', label: 'Less Paper Work' },
    ],
    services: [
      { icon: 'ri-folder-open-line', title: 'Case Management', desc: 'Track cases from intake to resolution with stage tracking, assigned attorneys, hearing dates, and notes.' },
      { icon: 'ri-calendar-check-line', title: 'Deadline Tracking', desc: 'Never miss a filing deadline, hearing date, or limitation period with automated alerts and calendar sync.' },
      { icon: 'ri-file-shield-2-line', title: 'Document Vault', desc: 'Secure document storage with version control, access permissions, and digital signature integration.' },
      { icon: 'ri-time-line', title: 'Time & Billing', desc: 'Track billable hours by case, generate itemized invoices, and manage retainer accounts.' },
      { icon: 'ri-contacts-book-line', title: 'Client Portal', desc: 'Give clients secure access to case updates, documents, invoices, and communication history.' },
      { icon: 'ri-search-line', title: 'Conflict Check', desc: 'Automated conflict-of-interest checks against your entire client and opposing party database.' },
    ],
    whyChooseUs: [
      { icon: 'ri-shield-check-line', title: 'Attorney-Client Privilege', desc: 'Encryption, access controls, and audit logs designed to protect privileged communications and documents.' },
      { icon: 'ri-whatsapp-line', title: 'Secure Client Updates', desc: 'Keep clients informed with case updates and hearing reminders via WhatsApp — encrypted and logged.' },
      { icon: 'ri-bar-chart-box-line', title: 'Practice Analytics', desc: 'Track case win rates, revenue per practice area, attorney utilization, and client acquisition costs.' },
      { icon: 'ri-team-line', title: 'Multi-Practice Support', desc: 'Manage litigation, corporate, IP, and other practice areas with dedicated pipelines and teams.' },
    ],
    differentiators: [
      { title: 'Indian Legal Workflows', desc: 'Court calendar integration, cause list tracking, eCourts sync, and Indian legal citation formats built in.' },
      { title: 'Retainer Management', desc: 'Track retainer balances, auto-deduct against time entries, and alert clients when retainer runs low.' },
      { title: 'Matter-Centric Design', desc: 'Everything revolves around matters/cases — not deals or opportunities. Designed by legal professionals.' },
      { title: 'Compliance Built In', desc: 'Bar council compliance, KYC documentation, anti-money laundering checks, and engagement letter templates.' },
    ],
    modules: [
      { name: 'Case/Matter Management', included: true },
      { name: 'Deadline & Hearing Tracker', included: true },
      { name: 'Document Management', included: true },
      { name: 'Time & Billing', included: true },
      { name: 'Client Portal', included: true },
      { name: 'Conflict Check', included: true },
      { name: 'WhatsApp Updates', included: true },
      { name: 'Court Calendar Sync', included: true },
      { name: 'Retainer Accounting', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'We eliminated missed deadlines completely. The case management and automatic court date reminders are indispensable.',
      author: 'Adv. Neha Gupta',
      role: 'Senior Partner',
      company: 'Gupta & Associates',
    },
    faqs: [
      { q: 'Is client data secure?', a: 'Yes. All data is encrypted, access is role-based, and audit logs track every action. Designed to protect attorney-client privilege.' },
      { q: 'Can I track court dates automatically?', a: 'Yes. Integrate with eCourts for automatic cause list updates, and get WhatsApp/email reminders before every hearing.' },
      { q: 'Does it support multiple practice areas?', a: 'Absolutely. Create separate pipelines, teams, and reporting for each practice area — litigation, corporate, IP, family law, etc.' },
      { q: 'How does billing work?', a: 'Track time entries per case, set hourly rates per attorney, and generate itemized invoices with retainer balance deductions.' },
    ],
    seo: {
      title: 'Legal CRM — Case Management & Law Firm Software | NexCRM',
      description: 'CRM for law firms and legal consultants. Manage cases, track deadlines, bill clients, and secure documents. Built for Indian legal practice.',
      keywords: 'legal CRM India, law firm CRM, case management software, advocate management system, legal billing software, court date tracker, legal practice management',
    },
  },

  manufacturing: {
    name: 'Manufacturing',
    color: 'yellow',
    icon: 'ri-settings-3-line',
    hero: {
      badge: { text: 'Manufacturing CRM', icon: 'ri-settings-3-line' },
      title: 'Streamline Orders. Scale Production.',
      subtitle: 'CRM for manufacturers, fabricators, and industrial businesses — manage inquiries, quotes, orders, and dealer networks from one platform.',
    },
    stats: [
      { value: '35%', label: 'Faster Quote-to-Order' },
      { value: '2x', label: 'Dealer Network Growth' },
      { value: '₹30Cr+', label: 'Orders Managed' },
      { value: '45%', label: 'Less Order Errors' },
    ],
    services: [
      { icon: 'ri-file-list-3-line', title: 'Quote & Order Management', desc: 'Generate detailed quotes with product specs, pricing, and terms. Convert approved quotes to orders with one click.' },
      { icon: 'ri-store-2-line', title: 'Dealer Portal', desc: 'Self-service portal for dealers to browse catalog, place orders, check inventory, and track shipments.' },
      { icon: 'ri-box-3-line', title: 'Inventory Tracking', desc: 'Real-time inventory levels for raw materials and finished goods with reorder alerts and stock movement logs.' },
      { icon: 'ri-truck-line', title: 'Dispatch & Logistics', desc: 'Manage dispatch schedules, generate challans and e-way bills, and track delivery status.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Payment & Credit', desc: 'Track receivables, manage credit limits per dealer, and automate payment reminders and overdue alerts.' },
      { icon: 'ri-bar-chart-grouped-line', title: 'Production Planning', desc: 'Link orders to production schedules, track job progress, and manage capacity planning.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Orders', desc: 'Dealers can inquire about stock, place repeat orders, and get dispatch updates directly on WhatsApp.' },
      { icon: 'ri-line-chart-line', title: 'Demand Forecasting', desc: 'Analyze order patterns to forecast demand, plan production, and prevent stockouts or overproduction.' },
      { icon: 'ri-shield-check-line', title: 'Quality Tracking', desc: 'Log quality checks, manage rejection rates, and trace issues back to specific batches or production runs.' },
      { icon: 'ri-global-line', title: 'Multi-Plant Support', desc: 'Manage multiple manufacturing units with plant-wise inventory, production, and dispatch tracking.' },
    ],
    differentiators: [
      { title: 'Built for Indian Manufacturing', desc: 'GST invoicing, e-way bills, HSN codes, and TDS handling — compliance features that Western CRMs lack.' },
      { title: 'Dealer Relationship Management', desc: 'Not just contacts — manage dealer tiers, credit limits, targets, incentive schemes, and performance scorecards.' },
      { title: 'Quote Configuration', desc: 'Complex product configurators with variants, add-ons, volume pricing, and custom specifications.' },
      { title: 'Order-to-Dispatch Tracking', desc: 'End-to-end visibility from order placement through production, quality check, packing, and dispatch.' },
    ],
    modules: [
      { name: 'Lead & Inquiry Management', included: true },
      { name: 'Quote Generator', included: true },
      { name: 'Order Management', included: true },
      { name: 'Dealer Portal', included: true },
      { name: 'Inventory Tracking', included: true },
      { name: 'Dispatch & Logistics', included: true },
      { name: 'Payment & Credit', included: true },
      { name: 'Quality Control', included: true },
      { name: 'WhatsApp Integration', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Enterprise',
    testimonial: {
      quote: 'Order processing errors dropped by 45%. Our dealers love the self-service portal — they can check stock and place orders without calling us.',
      author: 'Rajesh Agarwal',
      role: 'Managing Director',
      company: 'PrecisionTech Industries',
    },
    faqs: [
      { q: 'Can dealers place orders themselves?', a: 'Yes. The dealer portal lets dealers browse your catalog, check real-time inventory, place orders, and track dispatch status.' },
      { q: 'Does it handle GST and e-way bills?', a: 'Absolutely. Generate GST-compliant invoices, auto-calculate tax, and create e-way bills for interstate dispatch.' },
      { q: 'Can I track production against orders?', a: 'Yes. Link orders to production jobs, track progress by stage, and get alerts when jobs are ready for dispatch.' },
      { q: 'How does credit management work?', a: 'Set credit limits per dealer, track outstanding receivables, block orders when limits are exceeded, and send automated payment reminders.' },
    ],
    seo: {
      title: 'Manufacturing CRM — Orders, Inventory & Dealer Management | NexCRM',
      description: 'CRM for manufacturers. Manage quotes, orders, inventory, dealer networks, and dispatch. Built for Indian manufacturing with GST and e-way bills.',
      keywords: 'manufacturing CRM India, factory management CRM, dealer management system, inventory CRM, GST billing manufacturer, order management manufacturing, B2B CRM India',
    },
  },

  logistics: {
    name: 'Logistics',
    color: 'teal',
    icon: 'ri-truck-line',
    hero: {
      badge: { text: 'Logistics CRM', icon: 'ri-truck-line' },
      title: 'Move Faster. Deliver Smarter.',
      subtitle: 'CRM for logistics companies, freight forwarders, and courier services — manage shipments, clients, drivers, and operations from a single dashboard.',
    },
    stats: [
      { value: '30%', label: 'Faster Dispatch' },
      { value: '2.5x', label: 'Client Retention' },
      { value: '₹15Cr+', label: 'Freight Managed' },
      { value: '50%', label: 'Less Manual Tracking' },
    ],
    services: [
      { icon: 'ri-map-pin-line', title: 'Shipment Tracking', desc: 'Real-time tracking of shipments from pickup to delivery with status updates for clients and internal teams.' },
      { icon: 'ri-file-text-line', title: 'Quote & Rate Cards', desc: 'Generate instant freight quotes based on weight, distance, mode, and route. Maintain rate cards per client.' },
      { icon: 'ri-truck-line', title: 'Fleet Management', desc: 'Track vehicle availability, maintenance schedules, driver assignments, and fuel consumption.' },
      { icon: 'ri-exchange-funds-line', title: 'Route Optimization', desc: 'Optimize delivery routes for multi-drop shipments to reduce costs and improve delivery times.' },
      { icon: 'ri-file-list-3-line', title: 'Document Management', desc: 'Generate and store LR copies, POD, invoices, e-way bills, and customs documentation.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Billing & Reconciliation', desc: 'Automated invoicing, freight reconciliation, credit note management, and payment tracking per client.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Updates', desc: 'Automated shipment status updates to clients on WhatsApp — pickup confirmed, in transit, out for delivery, delivered.' },
      { icon: 'ri-bar-chart-box-line', title: 'Operations Analytics', desc: 'Track on-time delivery rates, vehicle utilization, route efficiency, and revenue per vehicle.' },
      { icon: 'ri-smartphone-line', title: 'Driver App', desc: 'Drivers get route details, pickup/delivery tasks, POD capture, and real-time communication on their phones.' },
      { icon: 'ri-links-line', title: 'API Integration', desc: 'Connect with e-commerce platforms, ERPs, and warehouse systems for automated order-to-shipment flow.' },
    ],
    differentiators: [
      { title: 'Indian Logistics Built-In', desc: 'E-way bills, LR generation, GST on freight, multi-modal support, and India-specific route optimization.' },
      { title: 'Client Self-Service', desc: 'Clients can create bookings, track shipments, download PODs, and view invoices from their own portal.' },
      { title: 'Multi-Modal Support', desc: 'Road, rail, air, and sea freight managed in one platform with mode-specific documentation and tracking.' },
      { title: 'POD Digitization', desc: 'Drivers capture proof of delivery with photos and e-signatures from the mobile app. Instantly available to clients.' },
    ],
    modules: [
      { name: 'Shipment Management', included: true },
      { name: 'Quote & Rate Cards', included: true },
      { name: 'Fleet Management', included: true },
      { name: 'Route Optimization', included: true },
      { name: 'Document Generation', included: true },
      { name: 'Billing & Invoicing', included: true },
      { name: 'Client Portal', included: true },
      { name: 'Driver App', included: true },
      { name: 'WhatsApp Tracking', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Dispatch is 30% faster now. Our clients love the WhatsApp tracking updates — we stopped getting "where is my shipment" calls.',
      author: 'Sanjay Mittal',
      role: 'Operations Head',
      company: 'SwiftFreight Logistics',
    },
    faqs: [
      { q: 'Can clients track shipments in real-time?', a: 'Yes. Clients get a tracking link via WhatsApp/email with real-time status updates from pickup to delivery.' },
      { q: 'Does it generate e-way bills?', a: 'Yes. Automatic e-way bill generation for interstate shipments with GST-compliant documentation.' },
      { q: 'Can drivers use it on their phones?', a: 'Yes. The driver app provides route details, pickup/delivery tasks, POD capture with photos, and real-time communication.' },
      { q: 'Does it support multiple transport modes?', a: 'Yes. Road, rail, air, and sea freight are supported with mode-specific tracking, documentation, and billing.' },
    ],
    seo: {
      title: 'Logistics CRM — Shipment Tracking & Fleet Management | NexCRM',
      description: 'CRM for logistics and freight companies. Track shipments, manage fleets, automate billing, and keep clients updated. Built for Indian logistics.',
      keywords: 'logistics CRM India, freight management CRM, shipment tracking software, fleet management CRM, transport CRM, courier management system, supply chain CRM',
    },
  },

  restaurant: {
    name: 'Restaurant',
    color: 'pink',
    icon: 'ri-restaurant-2-line',
    hero: {
      badge: { text: 'Restaurant CRM', icon: 'ri-restaurant-2-line' },
      title: 'Fill More Tables. Build Loyal Diners.',
      subtitle: 'CRM for restaurants, cafes, and cloud kitchens — manage reservations, customer preferences, feedback, and marketing campaigns to keep diners coming back.',
    },
    stats: [
      { value: '35%', label: 'More Repeat Visits' },
      { value: '4.6★', label: 'Avg Customer Rating' },
      { value: '₹8Cr+', label: 'Revenue Tracked' },
      { value: '2x', label: 'Loyalty Redemptions' },
    ],
    services: [
      { icon: 'ri-calendar-check-line', title: 'Table Reservations', desc: 'Online reservation system with table management, waitlist handling, and automated confirmation messages.' },
      { icon: 'ri-user-star-line', title: 'Customer Profiles', desc: 'Track dining preferences, allergies, favorite dishes, visit frequency, and average spend per customer.' },
      { icon: 'ri-gift-line', title: 'Loyalty Program', desc: 'Points-based rewards, birthday offers, and VIP tiers to incentivize repeat visits and higher spending.' },
      { icon: 'ri-feedback-line', title: 'Feedback Collection', desc: 'Post-meal feedback via QR codes and WhatsApp with sentiment analysis and issue escalation.' },
      { icon: 'ri-megaphone-line', title: 'Marketing Campaigns', desc: 'Send targeted promotions based on dining history — happy hour deals to weekday regulars, brunch offers to families.' },
      { icon: 'ri-star-line', title: 'Review Management', desc: 'Monitor and respond to Google, Zomato, and Swiggy reviews from one dashboard.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Marketing', desc: 'Send menu updates, event invitations, and personalized offers directly on WhatsApp. 90%+ open rates.' },
      { icon: 'ri-pie-chart-line', title: 'Revenue Insights', desc: 'Track revenue by day, time slot, table, and menu item. Identify your most profitable offerings.' },
      { icon: 'ri-smartphone-line', title: 'QR Menu & Ordering', desc: 'Digital menu with QR code access. Customers scan, browse, and order — reducing wait times.' },
      { icon: 'ri-links-line', title: 'Aggregator Integration', desc: 'Sync with Zomato, Swiggy, and other aggregators for unified order and review management.' },
    ],
    differentiators: [
      { title: 'Diner Intelligence', desc: 'Know your regulars — their favorite table, preferred cuisine, dietary restrictions, and spending patterns.' },
      { title: 'Built for Indian F&B', desc: 'GST-compliant billing, FSSAI tracking, multi-outlet support, and integration with Indian food aggregators.' },
      { title: 'Cloud Kitchen Ready', desc: 'Manage multiple brands from one kitchen with brand-wise menus, pricing, and delivery zone management.' },
      { title: 'Event & Catering CRM', desc: 'Manage catering inquiries, event bookings, menu customization, and follow-ups from the same platform.' },
    ],
    modules: [
      { name: 'Reservation System', included: true },
      { name: 'Customer Profiles', included: true },
      { name: 'Loyalty Program', included: true },
      { name: 'Feedback Collection', included: true },
      { name: 'Marketing Campaigns', included: true },
      { name: 'Review Management', included: true },
      { name: 'QR Menu', included: true },
      { name: 'WhatsApp Integration', included: true },
      { name: 'Catering Management', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'Repeat visits are up 35% since we started the loyalty program. The WhatsApp campaigns have better ROI than any food aggregator promotion.',
      author: 'Chef Arjun Reddy',
      role: 'Owner',
      company: 'Spice Route Kitchen',
    },
    faqs: [
      { q: 'Can customers reserve tables online?', a: 'Yes. Embed a reservation widget on your website or share a booking link on social media. Confirmations are sent via WhatsApp.' },
      { q: 'Does it work for cloud kitchens?', a: 'Yes. Manage multiple brands from one dashboard with separate menus, pricing, and delivery zones per brand.' },
      { q: 'How does the loyalty program work?', a: 'Customers earn points per visit or spend amount. Points can be redeemed for discounts, free items, or exclusive experiences.' },
      { q: 'Can I track Zomato and Swiggy reviews?', a: 'Yes. All aggregator reviews flow into one dashboard where you can monitor ratings, respond, and track sentiment trends.' },
    ],
    seo: {
      title: 'Restaurant CRM — Reservations, Loyalty & Marketing | NexCRM',
      description: 'CRM for restaurants and cafes. Manage reservations, build loyalty programs, collect feedback, and run targeted campaigns. Built for Indian F&B.',
      keywords: 'restaurant CRM India, cafe CRM software, restaurant reservation system, loyalty program restaurant, feedback management restaurant, food and beverage CRM, diner marketing tool',
    },
  },

  salon: {
    name: 'Salon & Spa',
    color: 'fuchsia',
    icon: 'ri-scissors-line',
    hero: {
      badge: { text: 'Salon CRM', icon: 'ri-scissors-line' },
      title: 'Book More Appointments. Keep Clients Coming Back.',
      subtitle: 'CRM for salons, spas, and beauty studios — manage appointments, stylists, memberships, and client preferences for a seamless experience.',
    },
    stats: [
      { value: '40%', label: 'More Repeat Bookings' },
      { value: '3x', label: 'Referral Growth' },
      { value: '₹4Cr+', label: 'Revenue Tracked' },
      { value: '50%', label: 'Less No-Shows' },
    ],
    services: [
      { icon: 'ri-calendar-check-line', title: 'Appointment Booking', desc: 'Online booking with stylist availability, service duration, and automated confirmations and reminders.' },
      { icon: 'ri-user-star-line', title: 'Client Profiles', desc: 'Track service history, product preferences, skin/hair type, allergies, and stylist preferences per client.' },
      { icon: 'ri-team-line', title: 'Staff Scheduling', desc: 'Manage stylist shifts, break times, leave, and workload distribution with visual scheduling.' },
      { icon: 'ri-vip-crown-line', title: 'Membership Plans', desc: 'Create membership tiers with service packages, product discounts, and priority booking privileges.' },
      { icon: 'ri-box-3-line', title: 'Product Inventory', desc: 'Track retail and professional product inventory with reorder alerts, usage tracking, and vendor management.' },
      { icon: 'ri-money-rupee-circle-line', title: 'POS & Billing', desc: 'Walk-in and appointment billing with service combos, tips, product sales, and split payments.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Reminders', desc: 'Reduce no-shows by 50% with automated appointment reminders and rescheduling options on WhatsApp.' },
      { icon: 'ri-line-chart-line', title: 'Revenue Analytics', desc: 'Track revenue by service, stylist, day, and client segment. Identify your most profitable services and time slots.' },
      { icon: 'ri-smartphone-line', title: 'Client App', desc: 'Branded booking app for clients to schedule appointments, view loyalty points, and browse services.' },
      { icon: 'ri-gift-line', title: 'Referral Program', desc: 'Reward clients for referrals with service credits, discounts, or loyalty points. Track referral chains.' },
    ],
    differentiators: [
      { title: 'Stylist Performance', desc: 'Track individual stylist revenue, client retention, service ratings, and rebooking rates for fair performance reviews.' },
      { title: 'Built for Indian Salons', desc: 'GST billing, UPI payments, walk-in + appointment mixed flow, and support for India-specific salon chains.' },
      { title: 'Service Memory', desc: 'Remember every client preference — hair color formula, preferred pressure level, product allergies — for consistently personalized service.' },
      { title: 'Multi-Location Support', desc: 'Manage multiple outlets with cross-location booking, inventory sharing, and consolidated reporting.' },
    ],
    modules: [
      { name: 'Appointment Booking', included: true },
      { name: 'Client Profiles', included: true },
      { name: 'Staff Scheduling', included: true },
      { name: 'Membership Plans', included: true },
      { name: 'Product Inventory', included: true },
      { name: 'POS & Billing', included: true },
      { name: 'Loyalty & Referrals', included: true },
      { name: 'WhatsApp Reminders', included: true },
      { name: 'Review Collection', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'No-shows dropped by half after we turned on WhatsApp reminders. The client profiles help our stylists deliver personalized experiences every time.',
      author: 'Pooja Nair',
      role: 'Founder',
      company: 'Glow Studio Salon',
    },
    faqs: [
      { q: 'Can clients book online?', a: 'Yes. Share your branded booking page on social media, Google, or your website. Clients pick a service, stylist, and time slot.' },
      { q: 'Does it handle walk-ins and appointments?', a: 'Yes. The POS handles both walk-in billing and appointment-based billing seamlessly with queue management.' },
      { q: 'Can I track product usage?', a: 'Yes. Deduct professional products used per service automatically and get reorder alerts when stock is low.' },
      { q: 'How does the membership work?', a: 'Create tiered memberships with service packages (e.g., 10 haircuts for ₹3000), product discounts, and priority booking. Auto-renewal supported.' },
    ],
    seo: {
      title: 'Salon CRM — Appointments, Memberships & Client Management | NexCRM',
      description: 'CRM for salons and spas. Manage appointments, track client preferences, run memberships, and reduce no-shows. Built for Indian beauty businesses.',
      keywords: 'salon CRM India, spa management software, beauty salon CRM, appointment booking salon, salon membership software, beauty parlour management, salon marketing tool',
    },
  },
};

export const industryList = Object.entries(industryData).map(([slug, data]) => ({
  slug,
  name: data.name,
  path: `/nexcrm/industries/${slug}`,
  icon: data.icon,
}));
