// Industry data for NexCRM industry landing pages
// Each key maps to a URL slug: /nexcrm/industries/:slug

export const industryData = {
  general: {
    name: 'General Business',
    color: 'blue',
    icon: 'ri-building-line',
    hero: {
      badge: { text: 'All-Purpose CRM', icon: 'ri-building-line' },
      title: 'The CRM That Adapts to Any Business',
      subtitle: 'Manage leads, close deals, and automate communications from a single dashboard — built for teams that need a CRM without the bloat.',
    },
    stats: [
      { value: '9+', label: 'Core Modules' },
      { value: '₹999', label: 'Starting Price/Mo' },
      { value: '14-Day', label: 'Free Trial' },
      { value: '6+', label: 'Communication Channels' },
    ],
    services: [
      { icon: 'ri-contacts-book-line', title: 'Lead & Deal Management', desc: 'Capture leads from forms, track them through a visual deal pipeline, and close more with activity-based selling.' },
      { icon: 'ri-mail-send-line', title: 'Email Campaigns', desc: 'Create email templates, run bulk mailing, and launch drip campaigns with open and click tracking built in.' },
      { icon: 'ri-whatsapp-line', title: 'WhatsApp & SMS', desc: 'Send WhatsApp broadcasts, SMS campaigns, and automated notifications — reach customers on the channels they use.' },
      { icon: 'ri-bar-chart-box-line', title: 'Analytics & Reports', desc: 'Dashboards for sales performance, lead sources, team activity, and revenue — with exportable reports.' },
      { icon: 'ri-robot-line', title: 'Workflow Automation', desc: 'Set up auto-responders, workflow triggers, and chatbot sequences to eliminate repetitive manual tasks.' },
      { icon: 'ri-file-text-line', title: 'Documents & Forms', desc: 'Build custom lead capture forms, store documents per contact, and manage your content pages with the built-in CMS.' },
    ],
    whyChooseUs: [
      { icon: 'ri-plug-line', title: 'Ready in Minutes', desc: 'No complicated setup. Sign up, pick your industry, and your CRM is pre-configured with the right modules.' },
      { icon: 'ri-shield-check-line', title: 'Role-Based Access', desc: 'Control who sees what with granular permissions for employees, managers, and admins.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Transparent Pricing', desc: 'Plans from ₹999/mo. No hidden fees, no per-user surcharges on base plans, no surprise invoices.' },
      { icon: 'ri-customer-service-line', title: 'Real Support', desc: 'Chat and email support from people who actually understand the product — not a script reader.' },
    ],
    differentiators: [
      { title: 'Built for India', desc: 'WhatsApp Business API, UPI payment tracking, and INR pricing — not a Western CRM with Indian pricing duct-taped on.' },
      { title: 'All-in-One Dashboard', desc: 'Leads, deals, customers, email campaigns, WhatsApp, team chat, and workflows — one login, one dashboard.' },
      { title: 'Industry-Adaptable', desc: 'Start with general CRM and switch to industry-specific modules (healthcare, real estate, etc.) as your business evolves.' },
      { title: 'White-Label Ready', desc: 'Agencies and resellers can rebrand the entire platform with custom domains and logos.' },
    ],
    modules: [
      { name: 'Lead Management', included: true },
      { name: 'Deal Pipeline', included: true },
      { name: 'Customer Database', included: true },
      { name: 'Email Campaigns & Templates', included: true },
      { name: 'WhatsApp & SMS', included: true },
      { name: 'Workflow Automation', included: true },
      { name: 'Lead Capture Forms', included: true },
      { name: 'Document Storage', included: true },
      { name: 'Reports & Analytics', included: true },
      { name: 'Team Chat & Notifications', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'NexCRM replaced three separate tools for us. Leads, emails, and WhatsApp — all in one place now.',
      author: 'Rahul Mehta',
      role: 'Founder',
      company: 'BrightPath Consulting',
    },
    faqs: [
      { q: 'Is NexCRM suitable for small businesses?', a: 'Yes. The Starter plan supports up to 3 team members and 500 leads — enough for most small businesses to get started.' },
      { q: 'Can I migrate from another CRM?', a: 'We support CSV imports for leads, contacts, and deals. Our team can assist with migration from spreadsheets or other CRMs.' },
      { q: 'Is there a free trial?', a: 'Every plan comes with a 14-day free trial. No credit card required.' },
      { q: 'What communication channels are included?', a: 'Email (templates, bulk, campaigns), WhatsApp (business API, broadcasts), SMS, in-app chat, push notifications, and AI chatbot.' },
    ],
    seo: {
      title: 'NexCRM — All-Purpose CRM for Growing Businesses | NexSpire Solutions',
      description: 'Manage leads, automate sales, and grow revenue with NexCRM. Affordable CRM built for Indian businesses with WhatsApp, email campaigns, and workflow automation.',
      keywords: 'CRM for small business India, affordable CRM software, lead management tool, sales automation CRM, WhatsApp CRM India, business CRM software, NexCRM',
    },
  },

  ecommerce: {
    name: 'E-Commerce',
    color: 'emerald',
    icon: 'ri-shopping-cart-2-line',
    hero: {
      badge: { text: 'E-Commerce CRM', icon: 'ri-shopping-cart-2-line' },
      title: 'Sell More. Manage Smarter. Grow Faster.',
      subtitle: 'CRM built for online stores — manage products, orders, inventory, shipping, returns, and customer relationships from one dashboard.',
    },
    stats: [
      { value: '10+', label: 'E-Commerce Modules' },
      { value: '₹999', label: 'Starting Price/Mo' },
      { value: 'Built-in', label: 'Vendor Management' },
      { value: 'Real-time', label: 'Inventory Tracking' },
    ],
    services: [
      { icon: 'ri-store-2-line', title: 'Product & Inventory', desc: 'Manage your full catalog with variants, pricing, categories, and real-time stock levels with reorder alerts.' },
      { icon: 'ri-shopping-bag-line', title: 'Order Management', desc: 'Track orders from placement through fulfillment — status updates, packing, and dispatch all in one view.' },
      { icon: 'ri-arrow-go-back-line', title: 'Returns Handling', desc: 'Process return requests, track refund status, and manage exchange workflows with automated customer updates.' },
      { icon: 'ri-truck-line', title: 'Shipping Management', desc: 'Manage shipping workflows, track dispatches, and coordinate deliveries across orders.' },
      { icon: 'ri-coupon-line', title: 'Coupons & Promotions', desc: 'Create discount codes, run promotional campaigns, and manage coupon rules from a dedicated module.' },
      { icon: 'ri-star-line', title: 'Reviews & Vendors', desc: 'Collect and manage product reviews, and coordinate with vendors through the built-in vendor management panel.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Notifications', desc: 'Order confirmations, shipping updates, and promotional broadcasts — sent where your customers already are.' },
      { icon: 'ri-line-chart-line', title: 'Sales Reports', desc: 'Track revenue, order volume, top products, and customer metrics with built-in reporting dashboards.' },
      { icon: 'ri-team-line', title: 'Vendor Coordination', desc: 'Onboard vendors, manage their product listings, and track vendor-level performance from one place.' },
      { icon: 'ri-shield-check-line', title: 'Secure Payments', desc: 'Integrated payment settings for Razorpay, UPI, and other gateways with transaction tracking.' },
    ],
    differentiators: [
      { title: 'End-to-End E-Commerce', desc: 'Products, orders, inventory, shipping, returns, reviews, coupons, and vendors — every e-commerce workflow in a single CRM.' },
      { title: 'CRM + E-Commerce', desc: 'Not just an order tracker. Full lead management, deal pipeline, and email campaigns alongside your store operations.' },
      { title: 'Indian Payment Stack', desc: 'Razorpay, UPI, and INR pricing baked in — not a Western plugin that doesn\'t understand Indian payment flows.' },
      { title: 'Flat Monthly Pricing', desc: 'No per-order fees, no transaction percentages. Pay a flat monthly rate regardless of order volume.' },
    ],
    modules: [
      { name: 'Products & Inventory', included: true },
      { name: 'Order Management', included: true },
      { name: 'Returns Processing', included: true },
      { name: 'Shipping Management', included: true },
      { name: 'Coupons & Discounts', included: true },
      { name: 'Customer Reviews', included: true },
      { name: 'Vendor Management', included: true },
      { name: 'Sales Reports', included: true },
      { name: 'CMS / Storefront', included: true },
      { name: 'Email & WhatsApp Campaigns', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Managing orders, inventory, and customer communication in one place cut our daily ops time in half.',
      author: 'Priya Sharma',
      role: 'Co-founder',
      company: 'UrbanKraft D2C',
    },
    faqs: [
      { q: 'Can I manage product variants and categories?', a: 'Yes. The product catalog supports variants (size, color, etc.), categories, pricing tiers, and real-time inventory tracking.' },
      { q: 'How does return handling work?', a: 'Customers or your team can initiate return requests. NexCRM tracks the return through approval, pickup, refund, or exchange.' },
      { q: 'Is vendor management included?', a: 'Yes. Onboard vendors, manage their listings, and track performance — included in Business and Enterprise plans.' },
      { q: 'Do you charge per order?', a: 'No. All plans have flat monthly pricing regardless of your order volume.' },
    ],
    seo: {
      title: 'E-Commerce CRM — Products, Orders & Inventory Management | NexCRM',
      description: 'CRM built for online stores. Manage products, orders, inventory, shipping, returns, and vendors. Full e-commerce operations in one dashboard.',
      keywords: 'ecommerce CRM India, online store CRM, order management CRM, inventory management ecommerce, vendor management CRM, product catalog CRM, ecommerce operations',
    },
  },

  realestate: {
    name: 'Real Estate',
    color: 'amber',
    icon: 'ri-home-smile-line',
    hero: {
      badge: { text: 'Real Estate CRM', icon: 'ri-home-smile-line' },
      title: 'Track Every Property. Close Every Deal.',
      subtitle: 'CRM for brokers, developers, and agencies — manage properties, listings, site visits, transactions, and agent teams from a single platform.',
    },
    stats: [
      { value: '8+', label: 'Real Estate Modules' },
      { value: 'Built-in', label: 'Agent Management' },
      { value: 'Visual', label: 'Deal Pipeline' },
      { value: 'Automated', label: 'Follow-up Sequences' },
    ],
    services: [
      { icon: 'ri-building-2-line', title: 'Property Management', desc: 'Manage your complete property inventory with details, photos, pricing, availability status, and unit-wise tracking.' },
      { icon: 'ri-file-list-3-line', title: 'Listings & Inquiries', desc: 'Publish listings, capture inquiries from multiple sources, and auto-assign to agents based on rules you define.' },
      { icon: 'ri-calendar-check-line', title: 'Site Visit Scheduling', desc: 'Schedule and track viewings with calendar management, automated reminders, and follow-up sequences.' },
      { icon: 'ri-exchange-funds-line', title: 'Transactions', desc: 'Track deals from booking to possession — manage payment milestones, agreements, and handover documentation.' },
      { icon: 'ri-team-line', title: 'Agent Management', desc: 'Manage your broker/agent team with lead assignments, performance tracking, and activity monitoring.' },
      { icon: 'ri-mail-send-line', title: 'Automated Communication', desc: 'WhatsApp property alerts, email drip sequences for prospects, and SMS reminders for site visits.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Follow-ups', desc: 'Automated property alerts and follow-ups on WhatsApp — the channel where Indian property buyers actually respond.' },
      { icon: 'ri-smartphone-line', title: 'Field-Ready CRM', desc: 'Your sales team works in the field. The CRM works on any device — check leads, log visits, update deals on the go.' },
      { icon: 'ri-pie-chart-line', title: 'Inventory Visibility', desc: 'See available units, sold inventory, and blocked units across projects in real-time dashboards.' },
      { icon: 'ri-funnel-line', title: 'Lead-to-Deal Pipeline', desc: 'Visual pipeline from first inquiry → site visit → negotiation → booking → registration — every stage tracked.' },
    ],
    differentiators: [
      { title: 'Built for Indian Realty', desc: 'Designed around how Indian real estate actually works — broker networks, site visits, payment milestones, and registry flows.' },
      { title: 'Agent Performance Tracking', desc: 'See which agents convert the most, which follow up on time, and which need coaching — data, not guesswork.' },
      { title: 'Property + CRM Combined', desc: 'Not just a contact list — full property inventory management alongside lead tracking and deal closure.' },
      { title: 'Multi-Project Support', desc: 'Builders managing multiple projects get project-wise inventory, agent assignments, and reporting in one account.' },
    ],
    modules: [
      { name: 'Property Management', included: true },
      { name: 'Listings', included: true },
      { name: 'Inquiry Capture', included: true },
      { name: 'Site Visit Scheduling', included: true },
      { name: 'Transactions & Deals', included: true },
      { name: 'Agent Management', included: true },
      { name: 'Lead Pipeline', included: true },
      { name: 'WhatsApp & Email Campaigns', included: true },
      { name: 'Document Storage', included: true },
      { name: 'CMS / Storefront', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'We stopped losing leads in spreadsheets. Every inquiry gets tracked, every site visit gets followed up — automatically.',
      author: 'Vikram Desai',
      role: 'Director',
      company: 'Horizon Realty Group',
    },
    faqs: [
      { q: 'Can I manage multiple projects?', a: 'Yes. Track properties, agents, and leads across multiple projects from a single dashboard with project-wise reporting.' },
      { q: 'Is it suitable for brokers and developers?', a: 'Yes. Whether you\'re a solo broker or a developer with a sales team, the CRM adapts with agent management and inventory modules.' },
      { q: 'How does site visit tracking work?', a: 'Schedule viewings, auto-send reminders to prospects, log visit outcomes, and trigger follow-up sequences — all in one flow.' },
      { q: 'Can agents access the system?', a: 'Yes. Create agent accounts with appropriate access levels to manage their leads, schedule visits, and update deal status.' },
    ],
    seo: {
      title: 'Real Estate CRM — Manage Properties, Leads & Agents | NexCRM',
      description: 'CRM for real estate brokers and developers. Manage properties, track site visits, handle transactions, and coordinate agent teams from one platform.',
      keywords: 'real estate CRM India, property management CRM, broker CRM software, real estate lead management, site visit scheduler, builder CRM, agent management CRM',
    },
  },

  services: {
    name: 'Professional Services',
    color: 'indigo',
    icon: 'ri-briefcase-line',
    hero: {
      badge: { text: 'Services CRM', icon: 'ri-briefcase-line' },
      title: 'Book Appointments. Manage Clients. Grow Revenue.',
      subtitle: 'CRM for consultants, agencies, and service professionals — manage bookings, schedules, service packages, and client relationships in one place.',
    },
    stats: [
      { value: '10+', label: 'Service Modules' },
      { value: 'Built-in', label: 'Booking Calendar' },
      { value: 'Unlimited', label: 'Service Categories' },
      { value: 'Automated', label: 'Reminders & Follow-ups' },
    ],
    services: [
      { icon: 'ri-calendar-todo-line', title: 'Booking Calendar', desc: 'Visual calendar for managing appointments, consultations, and service bookings with drag-and-drop scheduling.' },
      { icon: 'ri-list-check', title: 'Service Catalog', desc: 'Define your services with categories, durations, pricing, and descriptions — clients see exactly what you offer.' },
      { icon: 'ri-team-line', title: 'Staff Management', desc: 'Manage your team with scheduling, availability, service assignments, and workload balancing.' },
      { icon: 'ri-vip-crown-line', title: 'Packages & Memberships', desc: 'Create bundled service packages and membership plans with defined inclusions and validity periods.' },
      { icon: 'ri-time-line', title: 'Timesheets', desc: 'Track time spent per client, service, or project. Log hours and review team utilization reports.' },
      { icon: 'ri-contacts-book-line', title: 'Client Management', desc: 'Full client profiles with booking history, communication logs, packages purchased, and payment records.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Reminders', desc: 'Automated booking confirmations, reminders, and follow-ups on WhatsApp — reduce no-shows without lifting a finger.' },
      { icon: 'ri-line-chart-line', title: 'Service Analytics', desc: 'See which services sell best, which staff members are busiest, and where your revenue actually comes from.' },
      { icon: 'ri-repeat-line', title: 'Recurring Bookings', desc: 'Clients on retainer or memberships? Set up recurring appointments that auto-schedule at their preferred times.' },
      { icon: 'ri-file-text-line', title: 'Reports & CMS', desc: 'Built-in reports for revenue, bookings, and client retention. Plus a CMS to manage your service landing pages.' },
    ],
    differentiators: [
      { title: 'Booking-First Design', desc: 'Built around appointments and service delivery — not a sales CRM with a calendar bolted on as an afterthought.' },
      { title: 'Packages + Memberships', desc: 'Sell 10-session packages, monthly retainers, or annual memberships. Track remaining sessions automatically.' },
      { title: 'Staff-Aware Scheduling', desc: 'Bookings respect staff availability, service durations, and break times. No double-bookings, no conflicts.' },
      { title: 'Full CRM Underneath', desc: 'Leads, deals, email campaigns, and WhatsApp automation come standard — you get a booking engine AND a CRM.' },
    ],
    modules: [
      { name: 'Booking Calendar', included: true },
      { name: 'Appointment Management', included: true },
      { name: 'Service Catalog', included: true },
      { name: 'Staff Scheduling', included: true },
      { name: 'Packages & Memberships', included: true },
      { name: 'Timesheets', included: true },
      { name: 'Client Database', included: true },
      { name: 'Reports & Analytics', included: true },
      { name: 'Email & WhatsApp Campaigns', included: true },
      { name: 'CMS / Storefront', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'The booking calendar and WhatsApp reminders cut our no-show rate dramatically. Clients book themselves, we just deliver.',
      author: 'Ankit Jain',
      role: 'Managing Partner',
      company: 'Stride Digital Agency',
    },
    faqs: [
      { q: 'Is this suitable for freelancers?', a: 'Yes. The Starter plan is perfect for solo consultants with appointment scheduling, client management, and basic CRM included.' },
      { q: 'Can clients book appointments online?', a: 'Yes. Share a branded booking link on your website or social media. Clients pick a service, staff member, and time slot.' },
      { q: 'How do packages work?', a: 'Create packages (e.g., "10 sessions for ₹8000") or memberships (monthly/annual). The system tracks remaining sessions per client.' },
      { q: 'Is timesheet tracking included?', a: 'Yes. Log hours per client or service, review time reports, and track staff utilization — included in all plans.' },
    ],
    seo: {
      title: 'Professional Services CRM — Bookings, Appointments & Client Management | NexCRM',
      description: 'CRM for consultants, agencies, and service businesses. Manage appointments, track timesheets, sell packages, and grow your client base.',
      keywords: 'services CRM India, consulting CRM, agency CRM software, appointment booking CRM, service business management, client management CRM, freelancer CRM',
    },
  },

  education: {
    name: 'Education',
    color: 'violet',
    icon: 'ri-graduation-cap-line',
    hero: {
      badge: { text: 'Education CRM', icon: 'ri-graduation-cap-line' },
      title: 'Manage Courses. Track Students. Grow Enrollments.',
      subtitle: 'CRM for schools, coaching institutes, and edtech platforms — manage courses, batches, student records, attendance, and grades in one system.',
    },
    stats: [
      { value: '5+', label: 'Education Modules' },
      { value: 'Built-in', label: 'Attendance Tracking' },
      { value: 'Batch-wise', label: 'Student Management' },
      { value: 'Automated', label: 'Communication' },
    ],
    services: [
      { icon: 'ri-book-open-line', title: 'Course Management', desc: 'Define courses with syllabus, duration, fees, and capacity. Track active courses and enrollment numbers.' },
      { icon: 'ri-group-line', title: 'Student Records', desc: 'Centralized student database with enrollment details, batch assignment, contact info, and academic history.' },
      { icon: 'ri-calendar-check-line', title: 'Batch & Schedule', desc: 'Organize students into batches with timetables, faculty assignments, and batch-wise communication.' },
      { icon: 'ri-checkbox-circle-line', title: 'Attendance Tracking', desc: 'Mark and track attendance per batch and session. Generate attendance reports for students and parents.' },
      { icon: 'ri-file-chart-line', title: 'Grades & Results', desc: 'Record exam scores, generate grade sheets, and track student performance across terms and subjects.' },
      { icon: 'ri-mail-send-line', title: 'Student Communication', desc: 'WhatsApp and email updates to students — class schedules, attendance alerts, and exam reminders on autopilot.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Updates', desc: 'Attendance alerts, schedule changes, and exam notifications sent directly to students on WhatsApp.' },
      { icon: 'ri-funnel-line', title: 'Inquiry-to-Enrollment', desc: 'Capture inquiries, track them through your pipeline with the built-in CRM, and convert to enrolled students.' },
      { icon: 'ri-bar-chart-box-line', title: 'Performance Reports', desc: 'Batch-wise and student-wise performance reports to identify top performers and students who need attention.' },
      { icon: 'ri-lock-line', title: 'Data Privacy', desc: 'Student data encrypted with role-based access. Only authorized staff see sensitive information.' },
    ],
    differentiators: [
      { title: 'Academic Operations CRM', desc: 'Not an admissions funnel — actual course delivery tools with batches, attendance, grades, and student records.' },
      { title: 'Batch-Centric Design', desc: 'Everything organized by batch — students, schedules, attendance, communication. How institutes actually operate.' },
      { title: 'CRM + Academics Combined', desc: 'Lead capture and enrollment pipeline from the CRM side, plus course delivery tools on the operations side.' },
      { title: 'Built for Indian Institutes', desc: 'Designed for coaching centers, schools, and colleges in India — semester/term structure, WhatsApp-first communication.' },
    ],
    modules: [
      { name: 'Course Management', included: true },
      { name: 'Student Records', included: true },
      { name: 'Batch Management', included: true },
      { name: 'Enrollment Tracking', included: true },
      { name: 'Attendance Tracking', included: true },
      { name: 'Grades & Results', included: true },
      { name: 'Lead & Inquiry Pipeline', included: true },
      { name: 'WhatsApp & Email Communication', included: true },
      { name: 'Reports & Analytics', included: true },
      { name: 'CMS / Storefront', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Attendance tracking and batch management in one place saved us hours of spreadsheet work every week.',
      author: 'Dr. Meena Krishnan',
      role: 'Director',
      company: 'Vidya International School',
    },
    faqs: [
      { q: 'Is this suitable for coaching institutes?', a: 'Yes. NexCRM works for schools, coaching centers, and edtech platforms. Batch management and attendance are designed around how institutes operate.' },
      { q: 'Can I track student attendance?', a: 'Yes. Mark attendance per batch per session. Generate attendance reports and send alerts to students with low attendance.' },
      { q: 'How do grades and results work?', a: 'Enter exam scores, assign grades, and generate student-wise and batch-wise performance reports across terms and subjects.' },
      { q: 'Can I manage multiple branches?', a: 'Yes. Multi-branch support is available on Business and Enterprise plans with branch-wise data isolation and consolidated reporting.' },
    ],
    seo: {
      title: 'Education CRM — Courses, Students & Attendance Management | NexCRM',
      description: 'CRM for schools, coaching institutes, and edtech. Manage courses, batches, student records, attendance, and grades from one platform.',
      keywords: 'education CRM India, school management CRM, student management software, edtech CRM, attendance tracking system, coaching institute CRM, batch management software',
    },
  },

  healthcare: {
    name: 'Healthcare',
    color: 'rose',
    icon: 'ri-heart-pulse-line',
    hero: {
      badge: { text: 'Healthcare CRM', icon: 'ri-heart-pulse-line' },
      title: 'Better Patient Management. Better Outcomes.',
      subtitle: 'CRM for hospitals, clinics, and wellness centers — manage patients, appointments, prescriptions, lab results, billing, and medical records.',
    },
    stats: [
      { value: '10+', label: 'Healthcare Modules' },
      { value: 'Built-in', label: 'Prescription System' },
      { value: 'Complete', label: 'Medical Records' },
      { value: 'Integrated', label: 'Lab & Billing' },
    ],
    services: [
      { icon: 'ri-calendar-check-line', title: 'Appointment Scheduling', desc: 'Manage doctor availability, slot booking, automated confirmations, and reminders for patients.' },
      { icon: 'ri-user-heart-line', title: 'Patient Records', desc: 'Centralized patient profiles with demographics, visit history, allergies, conditions, and communication logs.' },
      { icon: 'ri-stethoscope-line', title: 'Prescriptions', desc: 'Create and manage prescriptions per visit — medications, dosage, instructions, and refill tracking.' },
      { icon: 'ri-test-tube-line', title: 'Lab Results', desc: 'Record lab orders, capture results, and link them to patient records for complete medical history tracking.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Billing & Insurance', desc: 'Generate bills per visit, track insurance claims, manage payment plans, and send automated payment reminders.' },
      { icon: 'ri-file-list-3-line', title: 'Medical Records', desc: 'Comprehensive medical records with visit notes, diagnosis, treatment plans, and document attachments.' },
    ],
    whyChooseUs: [
      { icon: 'ri-shield-check-line', title: 'Data Security', desc: 'Encrypted data storage, role-based access, and audit trails designed for sensitive patient information.' },
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Reminders', desc: 'Reduce no-shows with automated appointment reminders and pre-visit instructions sent via WhatsApp.' },
      { icon: 'ri-bar-chart-box-line', title: 'Operational Insights', desc: 'Track patient flow, revenue per department, doctor utilization, and appointment trends in real-time.' },
      { icon: 'ri-team-line', title: 'Staff Management', desc: 'Manage doctors, nurses, and support staff with schedules, assignments, and performance dashboards.' },
    ],
    differentiators: [
      { title: 'Patient-Centric Design', desc: 'Every feature revolves around the patient journey — from appointment to diagnosis to billing. Not a sales CRM relabeled.' },
      { title: 'Complete Clinical Workflow', desc: 'Appointments → prescriptions → lab orders → medical records → billing — the full clinical chain in one system.' },
      { title: 'Insurance & Billing Built In', desc: 'Track insurance claims alongside patient billing. No separate billing software needed for most clinics.' },
      { title: 'Built for Indian Healthcare', desc: 'WhatsApp patient communication, INR billing, and workflows designed around how Indian clinics actually operate.' },
    ],
    modules: [
      { name: 'Patient Records', included: true },
      { name: 'Appointment Scheduling', included: true },
      { name: 'Prescriptions', included: true },
      { name: 'Lab Results', included: true },
      { name: 'Medical Records', included: true },
      { name: 'Billing & Payments', included: true },
      { name: 'Insurance Tracking', included: true },
      { name: 'Staff Management', included: true },
      { name: 'Healthcare Dashboard', included: true },
      { name: 'Reports & Analytics', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Having patient records, prescriptions, and billing in one system transformed how our clinic operates. The WhatsApp reminders cut no-shows significantly.',
      author: 'Dr. Suresh Patel',
      role: 'Chief Medical Officer',
      company: 'LifeCare Clinics',
    },
    faqs: [
      { q: 'Is patient data secure?', a: 'Yes. All data is encrypted at rest and in transit. Role-based access and audit logs protect sensitive patient information.' },
      { q: 'Can patients book appointments online?', a: 'Yes. Patients can book via a branded booking page with real-time doctor availability and automated confirmations.' },
      { q: 'Does it support multiple doctors?', a: 'Yes. Each doctor gets their own schedule, patient list, and dashboard within the shared clinic account.' },
      { q: 'How does lab integration work?', a: 'Create lab orders from patient records, record results, and automatically link them to the patient\'s medical history.' },
    ],
    seo: {
      title: 'Healthcare CRM — Patient Management, Prescriptions & Billing | NexCRM',
      description: 'CRM for hospitals and clinics. Manage patients, appointments, prescriptions, lab results, and billing. Complete clinical workflow in one platform.',
      keywords: 'healthcare CRM India, hospital CRM software, patient management system, clinic appointment software, prescription management, medical records CRM, healthcare billing',
    },
  },

  hospitality: {
    name: 'Hospitality',
    color: 'orange',
    icon: 'ri-hotel-line',
    hero: {
      badge: { text: 'Hospitality CRM', icon: 'ri-hotel-line' },
      title: 'Manage Rooms. Delight Guests. Run Smooth Operations.',
      subtitle: 'CRM for hotels, resorts, and vacation properties — manage reservations, room inventory, guest profiles, housekeeping, and tour packages.',
    },
    stats: [
      { value: '7+', label: 'Hospitality Modules' },
      { value: 'Built-in', label: 'Housekeeping Tracker' },
      { value: 'Guest-wise', label: 'Profile & History' },
      { value: 'Integrated', label: 'Tour Management' },
    ],
    services: [
      { icon: 'ri-calendar-check-line', title: 'Reservation Management', desc: 'Manage room bookings, check-ins, check-outs, and availability with a centralized reservation calendar.' },
      { icon: 'ri-home-smile-line', title: 'Room Inventory', desc: 'Track room types, availability, status (occupied/vacant/maintenance), and pricing across your property.' },
      { icon: 'ri-user-star-line', title: 'Guest Profiles', desc: 'Maintain guest records with preferences, stay history, communication logs, and special requests.' },
      { icon: 'ri-checkbox-circle-line', title: 'Housekeeping', desc: 'Assign housekeeping tasks, track room cleaning status, and coordinate turnover between check-out and check-in.' },
      { icon: 'ri-map-pin-line', title: 'Tours & Destinations', desc: 'Manage tour packages, bookings, and destination listings — ideal for resorts offering local experiences.' },
      { icon: 'ri-mail-send-line', title: 'Guest Communication', desc: 'Pre-arrival messages, in-stay updates, and post-checkout follow-ups via WhatsApp and email.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Concierge', desc: 'Automated booking confirmations, check-in reminders, and post-stay feedback requests — all on WhatsApp.' },
      { icon: 'ri-bar-chart-box-line', title: 'Operations Dashboard', desc: 'Real-time view of occupancy, today\'s check-ins/outs, pending housekeeping tasks, and revenue.' },
      { icon: 'ri-team-line', title: 'Staff Coordination', desc: 'Front desk, housekeeping, and tour teams share one system — no radio chatter for room status updates.' },
      { icon: 'ri-global-line', title: 'Tour Packages', desc: 'Sell and manage local tours and experiences alongside room bookings — add-on revenue for your property.' },
    ],
    differentiators: [
      { title: 'Operations-First Design', desc: 'Reservations, housekeeping, and guest management in one workflow — not a generic CRM with "room" fields added.' },
      { title: 'Guest Memory', desc: 'Every preference remembered across stays — room type, dietary needs, special occasions. Personalized hospitality at scale.' },
      { title: 'Housekeeping Integration', desc: 'Housekeeping status linked directly to reservations — staff sees what needs cleaning as guests check out.' },
      { title: 'Tour Revenue Add-On', desc: 'Sell curated experiences and local tours to guests. Manage bookings, destinations, and tour schedules in the same system.' },
    ],
    modules: [
      { name: 'Reservation Management', included: true },
      { name: 'Room Inventory', included: true },
      { name: 'Guest Profiles', included: true },
      { name: 'Housekeeping Tracker', included: true },
      { name: 'Tour Packages', included: true },
      { name: 'Tour Bookings', included: true },
      { name: 'Destination Listings', included: true },
      { name: 'WhatsApp & Email Communication', included: true },
      { name: 'Lead & Inquiry Pipeline', included: true },
      { name: 'CMS / Storefront', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Housekeeping coordination used to be chaos. Now room status updates happen in real-time — the front desk always knows what\'s ready.',
      author: 'Aisha Khan',
      role: 'General Manager',
      company: 'Seaside Heritage Resort',
    },
    faqs: [
      { q: 'Can I manage room types and availability?', a: 'Yes. Define room types with pricing, amenities, and capacity. Track real-time availability across your property.' },
      { q: 'How does housekeeping tracking work?', a: 'Housekeeping tasks auto-generate on checkout. Staff mark rooms as cleaned, inspected, and ready — visible to the front desk instantly.' },
      { q: 'Can I sell tour packages to guests?', a: 'Yes. Create local tour packages, manage bookings, and list destinations — all included in the hospitality module.' },
      { q: 'Is it suitable for multi-property management?', a: 'Yes. Business and Enterprise plans support multi-property management with property-wise dashboards and consolidated reporting.' },
    ],
    seo: {
      title: 'Hospitality CRM — Hotel Reservations, Rooms & Guest Management | NexCRM',
      description: 'CRM for hotels and resorts. Manage reservations, rooms, guest profiles, housekeeping, and tour packages. Operations-first hospitality management.',
      keywords: 'hotel CRM India, hospitality CRM software, guest management system, resort booking CRM, room management software, housekeeping management, hotel operations CRM',
    },
  },

  travel: {
    name: 'Travel & Tourism',
    color: 'cyan',
    icon: 'ri-flight-takeoff-line',
    hero: {
      badge: { text: 'Travel CRM', icon: 'ri-flight-takeoff-line' },
      title: 'Manage Tours. Book Travelers. Grow Your Agency.',
      subtitle: 'CRM for travel agencies, tour operators, and DMCs — manage packages, itineraries, bookings, agents, and traveler profiles from one platform.',
    },
    stats: [
      { value: '11+', label: 'Travel Modules' },
      { value: 'Built-in', label: 'Itinerary Builder' },
      { value: 'Complete', label: 'Agent Management' },
      { value: 'Per-Traveler', label: 'Profile & Documents' },
    ],
    services: [
      { icon: 'ri-map-pin-line', title: 'Tour & Package Management', desc: 'Create tour packages with destinations, pricing, inclusions, and availability. Manage your complete tour catalog.' },
      { icon: 'ri-route-line', title: 'Itinerary Builder', desc: 'Build day-wise itineraries with activities, accommodations, transfers, and meals — shareable with travelers.' },
      { icon: 'ri-calendar-check-line', title: 'Booking Management', desc: 'Track bookings from inquiry to confirmation. Manage passenger lists, payment status, and trip details.' },
      { icon: 'ri-team-line', title: 'Agent Management', desc: 'Manage travel agents with lead assignments, booking tracking, and performance monitoring.' },
      { icon: 'ri-file-text-line', title: 'Travel Documents', desc: 'Collect and store passports, visas, insurance, and other travel documents per traveler — organized and accessible.' },
      { icon: 'ri-user-star-line', title: 'Traveler Profiles', desc: 'Maintain traveler profiles with preferences, past trips, dietary needs, and emergency contacts.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Itineraries', desc: 'Share itineraries and booking confirmations on WhatsApp. Travelers get trip details where they actually check.' },
      { icon: 'ri-bar-chart-box-line', title: 'Travel Dashboard', desc: 'Dedicated dashboard with upcoming tours, pending bookings, agent performance, and revenue metrics.' },
      { icon: 'ri-global-line', title: 'Destination Library', desc: 'Build a curated library of destinations with descriptions, images, and popular packages for quick itinerary creation.' },
      { icon: 'ri-funnel-line', title: 'Lead-to-Booking Pipeline', desc: 'Full CRM pipeline from travel inquiry → package selection → booking → payment → post-trip follow-up.' },
    ],
    differentiators: [
      { title: 'Travel-Specific CRM', desc: 'Not a generic CRM with "trip" fields — purpose-built modules for itineraries, packages, agents, and traveler documents.' },
      { title: 'Agent Network Management', desc: 'Manage sub-agents, track their bookings, and monitor which agents bring in the most business.' },
      { title: 'Document Management', desc: 'Passport copies, visa scans, insurance certificates — all linked to traveler profiles, not floating in email threads.' },
      { title: 'Full CRM + Travel Ops', desc: 'Lead management, email campaigns, and WhatsApp automation alongside tour operations — sales and delivery in one system.' },
    ],
    modules: [
      { name: 'Tour Packages', included: true },
      { name: 'Itineraries', included: true },
      { name: 'Tour Bookings', included: true },
      { name: 'Destinations', included: true },
      { name: 'Travel Agents', included: true },
      { name: 'Traveler Profiles', included: true },
      { name: 'Travel Documents', included: true },
      { name: 'Travel Dashboard', included: true },
      { name: 'Lead & Inquiry Pipeline', included: true },
      { name: 'WhatsApp & Email Campaigns', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'Managing itineraries, bookings, and agent performance in one place saved us hours every day. The document management alone was worth it.',
      author: 'Deepak Nair',
      role: 'Founder',
      company: 'Wanderlust Holidays',
    },
    faqs: [
      { q: 'Can I manage both B2C and B2B bookings?', a: 'Yes. Direct customer bookings and agent-sourced bookings are both tracked with separate attribution and reporting.' },
      { q: 'How does the itinerary builder work?', a: 'Build day-wise itineraries with destinations, activities, accommodations, and meals. Share via link or WhatsApp with travelers.' },
      { q: 'Can I track agent performance?', a: 'Yes. See which agents bring the most bookings, their conversion rates, and revenue contribution — all in the travel dashboard.' },
      { q: 'How does document management work?', a: 'Upload passport copies, visa documents, and insurance per traveler. Documents are linked to profiles and accessible from bookings.' },
    ],
    seo: {
      title: 'Travel CRM — Tours, Itineraries & Booking Management | NexCRM',
      description: 'CRM for travel agencies and tour operators. Manage packages, build itineraries, track bookings, and coordinate agents from one platform.',
      keywords: 'travel agency CRM India, tour operator CRM, itinerary builder, travel booking management, travel agent software, holiday package CRM, tourism CRM',
    },
  },

  fitness: {
    name: 'Fitness & Gym',
    color: 'red',
    icon: 'ri-boxing-line',
    hero: {
      badge: { text: 'Fitness CRM', icon: 'ri-boxing-line' },
      title: 'Manage Members. Run Classes. Grow Your Gym.',
      subtitle: 'CRM for gyms, yoga studios, and fitness centers — manage memberships, class schedules, trainers, workouts, subscriptions, and equipment.',
    },
    stats: [
      { value: '10+', label: 'Fitness Modules' },
      { value: 'Built-in', label: 'Subscription Billing' },
      { value: 'Per-Member', label: 'Workout Tracking' },
      { value: 'Dedicated', label: 'Fitness Dashboard' },
    ],
    services: [
      { icon: 'ri-group-line', title: 'Member Management', desc: 'Complete member profiles with membership status, joining date, attendance history, and fitness goals.' },
      { icon: 'ri-calendar-line', title: 'Class Scheduling', desc: 'Schedule group classes, personal training sessions, and workshops with capacity limits and trainer assignments.' },
      { icon: 'ri-user-settings-line', title: 'Trainer Management', desc: 'Manage trainers with schedules, member assignments, session logs, and availability tracking.' },
      { icon: 'ri-heart-pulse-line', title: 'Workout Plans', desc: 'Create and assign workout plans per member — exercises, sets, reps, and progress tracking over time.' },
      { icon: 'ri-repeat-line', title: 'Subscriptions', desc: 'Manage recurring membership subscriptions with auto-renewal, plan changes, and payment tracking.' },
      { icon: 'ri-settings-3-line', title: 'Equipment Tracking', desc: 'Track gym equipment inventory, maintenance schedules, and usage across your facility.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Engagement', desc: 'Workout reminders, class schedules, and renewal alerts delivered via WhatsApp — keep members engaged.' },
      { icon: 'ri-line-chart-line', title: 'Fitness Dashboard', desc: 'Dedicated dashboard with member stats, attendance trends, revenue metrics, and subscription health.' },
      { icon: 'ri-checkbox-circle-line', title: 'Attendance Tracking', desc: 'Track member attendance per class and session. Identify inactive members and trigger re-engagement.' },
      { icon: 'ri-bar-chart-box-line', title: 'Retention Insights', desc: 'See which members are at risk of dropping off based on attendance patterns and subscription status.' },
    ],
    differentiators: [
      { title: 'Fitness-First Design', desc: 'Not a generic CRM — purpose-built modules for memberships, workouts, classes, trainers, and gym equipment.' },
      { title: 'Workout + CRM Combined', desc: 'Member workout plans and progress tracking alongside lead management and marketing — sales and delivery unified.' },
      { title: 'Subscription Management', desc: 'Recurring billing, plan upgrades/downgrades, and automatic renewal handling. No separate billing tool needed.' },
      { title: 'Trainer-Member Linking', desc: 'Assign trainers to members, track session completion, and monitor trainer workload — data-driven team management.' },
    ],
    modules: [
      { name: 'Member Management', included: true },
      { name: 'Class Scheduling', included: true },
      { name: 'Trainer Management', included: true },
      { name: 'Workout Plans', included: true },
      { name: 'Subscriptions & Billing', included: true },
      { name: 'Attendance Tracking', included: true },
      { name: 'Equipment Tracking', included: true },
      { name: 'Fitness Dashboard', included: true },
      { name: 'Lead & Inquiry Pipeline', included: true },
      { name: 'WhatsApp & Email Campaigns', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'Having member management, workout tracking, and subscription billing in one place simplified everything. We finally stopped juggling spreadsheets.',
      author: 'Ravi Kumar',
      role: 'Owner',
      company: 'IronFit Gym Chain',
    },
    faqs: [
      { q: 'Can members book classes online?', a: 'Yes. Members can view the class schedule and book available slots. The system respects capacity limits and trainer availability.' },
      { q: 'How does subscription billing work?', a: 'Set up membership plans with pricing and duration. The system handles renewals, sends reminders, and tracks payment status.' },
      { q: 'Can I assign workout plans to members?', a: 'Yes. Create exercise plans with sets, reps, and progression. Assign plans to members and track their progress over time.' },
      { q: 'Does it track gym equipment?', a: 'Yes. Maintain an equipment inventory with purchase dates, maintenance schedules, and status tracking.' },
    ],
    seo: {
      title: 'Fitness CRM — Gym Membership, Workouts & Class Management | NexCRM',
      description: 'CRM for gyms and fitness centers. Manage memberships, subscriptions, class schedules, trainers, and workout plans. Built for Indian fitness businesses.',
      keywords: 'gym CRM India, fitness center CRM, gym management software, membership management system, workout tracking CRM, gym billing software, fitness studio CRM',
    },
  },

  legal: {
    name: 'Legal',
    color: 'slate',
    icon: 'ri-scales-3-line',
    hero: {
      badge: { text: 'Legal CRM', icon: 'ri-scales-3-line' },
      title: 'Manage Cases. Track Deadlines. Bill Accurately.',
      subtitle: 'CRM for law firms, advocates, and legal consultants — manage cases, court dates, client files, time tracking, invoicing, and task assignments.',
    },
    stats: [
      { value: '8+', label: 'Legal Modules' },
      { value: 'Built-in', label: 'Time Tracking' },
      { value: 'Case-wise', label: 'Document Management' },
      { value: 'Automated', label: 'Deadline Reminders' },
    ],
    services: [
      { icon: 'ri-folder-open-line', title: 'Case Management', desc: 'Track cases from intake to resolution — stages, assigned lawyers, hearing dates, notes, and linked documents.' },
      { icon: 'ri-calendar-check-line', title: 'Court Date Tracking', desc: 'Schedule and track hearing dates and filing deadlines with automated alerts so nothing gets missed.' },
      { icon: 'ri-time-line', title: 'Time Tracking', desc: 'Log billable hours per case, lawyer, or task. Review timesheets and calculate billing at defined hourly rates.' },
      { icon: 'ri-money-rupee-circle-line', title: 'Invoicing', desc: 'Generate detailed invoices from logged time entries with itemized breakdowns, tax calculations, and payment tracking.' },
      { icon: 'ri-file-shield-2-line', title: 'Document Vault', desc: 'Secure case document storage with organization by matter, version tracking, and role-based access control.' },
      { icon: 'ri-checkbox-circle-line', title: 'Tasks & Assignments', desc: 'Create and assign tasks per case. Track deadlines, completion status, and workload across your legal team.' },
    ],
    whyChooseUs: [
      { icon: 'ri-shield-check-line', title: 'Secure & Private', desc: 'Encryption, access controls, and audit logs designed to protect confidential client information and case data.' },
      { icon: 'ri-whatsapp-line', title: 'Client Updates', desc: 'Keep clients informed with case status updates and hearing reminders via WhatsApp — timely and logged.' },
      { icon: 'ri-team-line', title: 'Lawyer Management', desc: 'Manage your team of lawyers and associates with case assignments, schedules, and workload visibility.' },
      { icon: 'ri-bar-chart-box-line', title: 'Practice Analytics', desc: 'Track case load, billable hours, revenue per lawyer, and payment collection trends across your practice.' },
    ],
    differentiators: [
      { title: 'Matter-Centric Design', desc: 'Everything revolves around cases — not deals or contacts. Built for how legal professionals actually work.' },
      { title: 'Time-to-Invoice Flow', desc: 'Log hours → review timesheets → generate invoices → track payments. Seamless billing workflow, no export/import.' },
      { title: 'Task + Case Linking', desc: 'Every task is linked to a case. Your team sees what needs doing, for which matter, by when.' },
      { title: 'Full CRM Underneath', desc: 'Lead capture, client management, email campaigns, and WhatsApp — market your practice while managing cases.' },
    ],
    modules: [
      { name: 'Case Management', included: true },
      { name: 'Client Database', included: true },
      { name: 'Court Date Tracking', included: true },
      { name: 'Case Documents', included: true },
      { name: 'Time Tracking', included: true },
      { name: 'Invoicing & Billing', included: true },
      { name: 'Lawyer Management', included: true },
      { name: 'Task Assignments', included: true },
      { name: 'Lead & Inquiry Pipeline', included: true },
      { name: 'CMS / Storefront', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Missed deadlines are a thing of the past. Case management with time tracking and invoicing in one system is exactly what we needed.',
      author: 'Adv. Neha Gupta',
      role: 'Senior Partner',
      company: 'Gupta & Associates',
    },
    faqs: [
      { q: 'Is client data secure?', a: 'Yes. All data is encrypted. Role-based access and audit logs ensure only authorized team members see case information.' },
      { q: 'Can I track court dates and deadlines?', a: 'Yes. Schedule hearing dates and filing deadlines with automated reminders via email and WhatsApp.' },
      { q: 'Does it support multiple practice areas?', a: 'Yes. Organize cases by practice area (litigation, corporate, IP, etc.) with separate pipelines and team assignments.' },
      { q: 'How does billing work?', a: 'Log time entries per case, set hourly rates per lawyer, and generate itemized invoices. Track payments and outstanding balances.' },
    ],
    seo: {
      title: 'Legal CRM — Case Management, Time Tracking & Invoicing | NexCRM',
      description: 'CRM for law firms and advocates. Manage cases, track court dates, log billable hours, and generate invoices. Built for Indian legal practice.',
      keywords: 'legal CRM India, law firm CRM, case management software, advocate management system, legal billing software, court date tracker, legal practice management',
    },
  },

  manufacturing: {
    name: 'Manufacturing',
    color: 'yellow',
    icon: 'ri-settings-3-line',
    hero: {
      badge: { text: 'Manufacturing CRM', icon: 'ri-settings-3-line' },
      title: 'From Raw Material to Finished Product — All in One.',
      subtitle: 'The most comprehensive manufacturing CRM available — 26+ modules for production, inventory, quality, MRP, equipment, invoicing, and advanced analytics.',
    },
    stats: [
      { value: '26+', label: 'Manufacturing Modules' },
      { value: 'End-to-End', label: 'Production Tracking' },
      { value: 'Built-in', label: 'MRP Planning' },
      { value: 'Advanced', label: 'Quality & SPC' },
    ],
    services: [
      { icon: 'ri-settings-3-line', title: 'Production & Scheduling', desc: 'Manage production runs with scheduling, work orders, batch tracking, and stage-wise progress monitoring.' },
      { icon: 'ri-box-3-line', title: 'Inventory & Materials', desc: 'Track raw materials, finished goods, material movements, and stock levels with supplier coordination.' },
      { icon: 'ri-shield-check-line', title: 'Quality Control', desc: 'Standard and advanced quality checks, rejection tracking, SPC analytics, and batch-level traceability.' },
      { icon: 'ri-file-list-3-line', title: 'Orders & Invoicing', desc: 'Sales orders, purchase orders, GST-compliant invoicing, and automated invoice workflows from order to payment.' },
      { icon: 'ri-tools-line', title: 'Equipment & Maintenance', desc: 'Equipment registry, maintenance scheduling, predictive maintenance alerts, and IoT sensor integration.' },
      { icon: 'ri-bar-chart-grouped-line', title: 'MRP & Planning', desc: 'Material Requirements Planning, ATP (Available-to-Promise) planning, and product configurator for complex assemblies.' },
    ],
    whyChooseUs: [
      { icon: 'ri-line-chart-line', title: 'Advanced Analytics', desc: 'SPC analytics, production reports, quality trends, and predictive maintenance insights — data-driven manufacturing.' },
      { icon: 'ri-links-line', title: 'IoT Integration', desc: 'Connect shop floor sensors for real-time equipment monitoring, predictive alerts, and automated data capture.' },
      { icon: 'ri-whatsapp-line', title: 'Supplier Communication', desc: 'Purchase order updates, material delivery tracking, and payment reminders via WhatsApp and email.' },
      { icon: 'ri-shield-user-line', title: 'Warranty & RMA', desc: 'Track warranties, process return authorizations, and manage warranty claims — complete post-sales support.' },
    ],
    differentiators: [
      { title: 'India\'s Deepest Manufacturing CRM', desc: '26+ purpose-built modules — production, scheduling, MRP, quality (basic + advanced), SPC, IoT, predictive maintenance, and configurator.' },
      { title: 'Batch-Level Traceability', desc: 'Trace every unit from raw material receipt through production, quality checks, and shipment. Complete audit trail.' },
      { title: 'Invoice Automation', desc: 'Auto-generate invoices from sales orders, manage GST calculations, and run invoice reports — no separate accounting tool.' },
      { title: 'Shop Floor to Front Office', desc: 'Production, quality, inventory, and invoicing in one system. No integrations needed between shop floor and commercial teams.' },
    ],
    modules: [
      { name: 'Production Management', included: true },
      { name: 'Production Scheduling', included: true },
      { name: 'Work Orders', included: true },
      { name: 'Batch Tracking', included: true },
      { name: 'Raw Materials & Suppliers', included: true },
      { name: 'Material Movements', included: true },
      { name: 'Manufacturing Inventory', included: true },
      { name: 'Quality Control (Basic + Advanced)', included: true },
      { name: 'SPC Analytics', included: true },
      { name: 'MRP Planning', included: true },
      { name: 'Sales Orders', included: true },
      { name: 'Purchase Orders', included: true },
      { name: 'Invoicing & Automation', included: true },
      { name: 'Equipment Maintenance', included: true },
      { name: 'IoT Integration', included: true },
      { name: 'Predictive Maintenance', included: true },
      { name: 'Product Configurator', included: true },
      { name: 'ATP Planning', included: true },
      { name: 'Warranty & RMA', included: true },
      { name: 'Manufacturing Dashboard & Reports', included: true },
    ],
    recommendedTier: 'Enterprise',
    testimonial: {
      quote: 'We replaced three separate systems — ERP, quality tracking, and invoicing — with NexCRM. The batch traceability alone paid for itself.',
      author: 'Rajesh Agarwal',
      role: 'Managing Director',
      company: 'PrecisionTech Industries',
    },
    faqs: [
      { q: 'How many modules does manufacturing include?', a: '26+ modules covering production, scheduling, inventory, quality (basic and advanced), MRP, equipment, invoicing, IoT, and analytics.' },
      { q: 'Does it support batch tracking?', a: 'Yes. Full batch-level traceability from raw material receipt through production, quality checks, and final shipment.' },
      { q: 'Can I connect shop floor equipment?', a: 'Yes. IoT integration supports sensor data for real-time monitoring, predictive maintenance, and automated quality data capture.' },
      { q: 'Does it handle GST invoicing?', a: 'Yes. GST-compliant invoicing with auto-calculation, invoice automation from sales orders, and detailed invoice reports.' },
    ],
    seo: {
      title: 'Manufacturing CRM — Production, Quality, MRP & Invoicing | NexCRM',
      description: 'India\'s most comprehensive manufacturing CRM. 26+ modules for production, scheduling, quality control, MRP planning, equipment maintenance, and invoicing.',
      keywords: 'manufacturing CRM India, production management CRM, factory management software, MRP planning CRM, quality control manufacturing, batch tracking system, manufacturing ERP India',
    },
  },

  logistics: {
    name: 'Logistics',
    color: 'teal',
    icon: 'ri-truck-line',
    hero: {
      badge: { text: 'Logistics CRM', icon: 'ri-truck-line' },
      title: 'Track Shipments. Manage Fleets. Serve Clients.',
      subtitle: 'CRM for logistics companies, freight forwarders, and courier services — manage shipments, tracking, vehicles, drivers, warehouses, and routes.',
    },
    stats: [
      { value: '9+', label: 'Logistics Modules' },
      { value: 'Real-time', label: 'Shipment Tracking' },
      { value: 'Built-in', label: 'Fleet Management' },
      { value: 'Dedicated', label: 'Logistics Dashboard' },
    ],
    services: [
      { icon: 'ri-map-pin-line', title: 'Shipment Management', desc: 'Create and manage shipments with pickup/delivery details, status tracking, and client assignment.' },
      { icon: 'ri-compass-line', title: 'Live Tracking', desc: 'Track shipment status from pickup through transit to delivery — updated in real-time for internal teams and clients.' },
      { icon: 'ri-truck-line', title: 'Vehicle Management', desc: 'Track your fleet — vehicle details, availability, maintenance schedules, and assignment to shipments.' },
      { icon: 'ri-user-star-line', title: 'Driver Management', desc: 'Manage drivers with profiles, license details, vehicle assignments, and trip history.' },
      { icon: 'ri-building-line', title: 'Warehouse Management', desc: 'Track warehouse locations, capacity, and inventory. Coordinate inbound and outbound movements.' },
      { icon: 'ri-route-line', title: 'Route Management', desc: 'Define and manage delivery routes with waypoints, estimated timings, and vehicle assignments.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Updates', desc: 'Automated shipment status updates to clients — pickup confirmed, in transit, out for delivery, delivered.' },
      { icon: 'ri-bar-chart-box-line', title: 'Logistics Dashboard', desc: 'Real-time operations dashboard with active shipments, vehicle utilization, driver status, and delivery metrics.' },
      { icon: 'ri-funnel-line', title: 'Client CRM Pipeline', desc: 'Full lead management and deal pipeline alongside operations — win new logistics clients while managing existing ones.' },
      { icon: 'ri-file-text-line', title: 'Document Management', desc: 'Store and generate shipping documents, delivery receipts, and invoices per shipment.' },
    ],
    differentiators: [
      { title: 'Operations + CRM', desc: 'Not just a fleet tracker or a CRM — both combined. Manage client relationships AND shipment operations in one system.' },
      { title: 'End-to-End Visibility', desc: 'Shipment → vehicle → driver → route → warehouse — every logistics entity linked and trackable from one dashboard.' },
      { title: 'Fleet Intelligence', desc: 'Know which vehicles are available, which are in maintenance, and which drivers are assigned — at any given moment.' },
      { title: 'Client Communication', desc: 'Automated status updates on WhatsApp and email. Clients stay informed without calling your ops team.' },
    ],
    modules: [
      { name: 'Shipment Management', included: true },
      { name: 'Shipment Tracking', included: true },
      { name: 'Vehicle Management', included: true },
      { name: 'Driver Management', included: true },
      { name: 'Warehouse Management', included: true },
      { name: 'Route Management', included: true },
      { name: 'Logistics Dashboard', included: true },
      { name: 'Lead & Client Pipeline', included: true },
      { name: 'WhatsApp & Email Communication', included: true },
      { name: 'CMS / Storefront', included: true },
    ],
    recommendedTier: 'Business',
    testimonial: {
      quote: 'Clients stopped calling to ask "where is my shipment?" — the WhatsApp tracking updates handle it automatically now.',
      author: 'Sanjay Mittal',
      role: 'Operations Head',
      company: 'SwiftFreight Logistics',
    },
    faqs: [
      { q: 'Can clients track shipments in real-time?', a: 'Yes. Shipment status updates are available in real-time via the logistics dashboard and automated WhatsApp notifications.' },
      { q: 'How does vehicle management work?', a: 'Track vehicle details, availability status, maintenance schedules, and assignment history. Know which vehicles are free at a glance.' },
      { q: 'Can I manage multiple warehouses?', a: 'Yes. Track multiple warehouse locations with capacity, inventory levels, and inbound/outbound movement logs.' },
      { q: 'Does it support route planning?', a: 'Yes. Define routes with stops, estimated timings, and distances. Assign routes to vehicles and track progress.' },
    ],
    seo: {
      title: 'Logistics CRM — Shipment Tracking, Fleet & Warehouse Management | NexCRM',
      description: 'CRM for logistics and freight companies. Track shipments, manage fleets, coordinate drivers, and operate warehouses. Built for Indian logistics.',
      keywords: 'logistics CRM India, freight management CRM, shipment tracking software, fleet management CRM, transport CRM, warehouse management, supply chain CRM',
    },
  },

  restaurant: {
    name: 'Restaurant',
    color: 'pink',
    icon: 'ri-restaurant-2-line',
    hero: {
      badge: { text: 'Restaurant CRM', icon: 'ri-restaurant-2-line' },
      title: 'Manage Orders. Run Your Kitchen. Know Your Diners.',
      subtitle: 'CRM for restaurants, cafes, and cloud kitchens — manage menus, orders, tables, kitchen operations, inventory, staff scheduling, and customer data.',
    },
    stats: [
      { value: '11+', label: 'Restaurant Modules' },
      { value: 'Built-in', label: 'Kitchen Management' },
      { value: 'Real-time', label: 'Table & Waitlist' },
      { value: 'Dedicated', label: 'Restaurant Dashboard' },
    ],
    services: [
      { icon: 'ri-restaurant-line', title: 'Menu Management', desc: 'Create and manage your full menu with categories, pricing, descriptions, availability, and dietary tags.' },
      { icon: 'ri-shopping-bag-line', title: 'Order Management', desc: 'Track dine-in and takeaway orders from placement through kitchen to delivery — with status tracking.' },
      { icon: 'ri-layout-grid-line', title: 'Table & Reservations', desc: 'Manage table layout, accept reservations, and handle walk-in seating with real-time availability.' },
      { icon: 'ri-fire-line', title: 'Kitchen Management', desc: 'Kitchen display for incoming orders, prep status, and order completion. Keep front-of-house and kitchen in sync.' },
      { icon: 'ri-box-3-line', title: 'Inventory Tracking', desc: 'Track ingredient and supply inventory with stock levels, usage monitoring, and reorder alerts.' },
      { icon: 'ri-time-line', title: 'Waitlist & Scheduling', desc: 'Manage walk-in waitlists during peak hours and staff scheduling with shift management.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Notifications', desc: 'Reservation confirmations, order updates, and promotional messages to customers via WhatsApp.' },
      { icon: 'ri-bar-chart-box-line', title: 'Restaurant Dashboard', desc: 'Real-time dashboard with today\'s orders, revenue, table occupancy, kitchen queue, and customer metrics.' },
      { icon: 'ri-user-star-line', title: 'Customer Database', desc: 'Track dining preferences, visit history, average spend, and special occasions for personalized service.' },
      { icon: 'ri-file-chart-line', title: 'Revenue Reports', desc: 'Track revenue by day, time slot, and menu item. See which dishes sell best and when traffic peaks.' },
    ],
    differentiators: [
      { title: 'Kitchen-Connected CRM', desc: 'Orders flow from table/takeaway directly to the kitchen display. No tickets lost, no miscommunication.' },
      { title: 'Waitlist + Reservations', desc: 'Handle both advance reservations and walk-in waitlists from one table management system.' },
      { title: 'Staff Scheduling Built In', desc: 'Manage server and kitchen staff shifts, breaks, and availability — alongside your restaurant operations.' },
      { title: 'Full CRM + Restaurant Ops', desc: 'Customer database, lead management, and email/WhatsApp campaigns alongside menu, orders, and kitchen management.' },
    ],
    modules: [
      { name: 'Menu Management', included: true },
      { name: 'Order Management', included: true },
      { name: 'Table Management', included: true },
      { name: 'Table Reservations', included: true },
      { name: 'Kitchen Display', included: true },
      { name: 'Restaurant Inventory', included: true },
      { name: 'Waitlist', included: true },
      { name: 'Staff Scheduling', included: true },
      { name: 'Customer Database', included: true },
      { name: 'Restaurant Dashboard & Reports', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'The kitchen display changed everything. Orders go straight from the table to the kitchen — no more lost tickets or shouting across the floor.',
      author: 'Chef Arjun Reddy',
      role: 'Owner',
      company: 'Spice Route Kitchen',
    },
    faqs: [
      { q: 'Can customers reserve tables online?', a: 'Yes. Share a booking link on your website or social media. Customers pick a date, time, and party size with instant confirmation.' },
      { q: 'How does the kitchen display work?', a: 'Orders appear on the kitchen display as they\'re placed. Kitchen staff update prep status, and the system notifies servers when food is ready.' },
      { q: 'Does it handle walk-in waitlists?', a: 'Yes. Add walk-in parties to the waitlist with estimated wait times. Notify customers via SMS or WhatsApp when their table is ready.' },
      { q: 'Can I track ingredient inventory?', a: 'Yes. Track stock levels, monitor usage, and get alerts when supplies need reordering.' },
    ],
    seo: {
      title: 'Restaurant CRM — Menu, Orders, Kitchen & Table Management | NexCRM',
      description: 'CRM for restaurants and cafes. Manage menus, orders, tables, kitchen operations, inventory, and staff scheduling. Built for Indian F&B businesses.',
      keywords: 'restaurant CRM India, cafe management software, restaurant order management, kitchen display system, table reservation system, restaurant inventory, F&B management CRM',
    },
  },

  salon: {
    name: 'Salon & Spa',
    color: 'fuchsia',
    icon: 'ri-scissors-line',
    hero: {
      badge: { text: 'Salon CRM', icon: 'ri-scissors-line' },
      title: 'Book Appointments. Manage Staff. Showcase Your Work.',
      subtitle: 'CRM for salons, spas, and beauty studios — manage bookings, services, staff, packages, products, customer profiles, and a portfolio gallery.',
    },
    stats: [
      { value: '9+', label: 'Salon Modules' },
      { value: 'Built-in', label: 'Service Packages' },
      { value: 'Per-Client', label: 'Preference Tracking' },
      { value: 'Dedicated', label: 'Portfolio Gallery' },
    ],
    services: [
      { icon: 'ri-calendar-check-line', title: 'Appointment Booking', desc: 'Online booking with stylist availability, service duration, and automated confirmations and reminders.' },
      { icon: 'ri-list-check', title: 'Service Management', desc: 'Define your service menu with categories, pricing, durations, and descriptions. Update availability instantly.' },
      { icon: 'ri-team-line', title: 'Staff Management', desc: 'Manage stylists and therapists with schedules, service specializations, availability, and performance tracking.' },
      { icon: 'ri-vip-crown-line', title: 'Packages & Combos', desc: 'Create service packages (e.g., "10 sessions for ₹5000") and combo offers. Track package redemption per client.' },
      { icon: 'ri-box-3-line', title: 'Product Inventory', desc: 'Track retail and professional products with stock levels, usage per service, and reorder alerts.' },
      { icon: 'ri-image-line', title: 'Gallery & Portfolio', desc: 'Showcase your work with a photo gallery — before/after shots, styling portfolios, and featured transformations.' },
    ],
    whyChooseUs: [
      { icon: 'ri-whatsapp-line', title: 'WhatsApp Reminders', desc: 'Reduce no-shows with automated appointment reminders and rescheduling options via WhatsApp.' },
      { icon: 'ri-user-star-line', title: 'Client Preferences', desc: 'Track every client\'s service history, stylist preference, product usage, skin/hair type, and special notes.' },
      { icon: 'ri-bar-chart-box-line', title: 'Salon Dashboard', desc: 'Dedicated dashboard with today\'s appointments, revenue, staff utilization, and top services.' },
      { icon: 'ri-line-chart-line', title: 'Revenue Insights', desc: 'Track revenue by service, stylist, day, and client segment. Identify your best-performing services and time slots.' },
    ],
    differentiators: [
      { title: 'Booking + Gallery Combined', desc: 'Clients book appointments AND browse your portfolio gallery from the same platform — book what they see.' },
      { title: 'Service Memory', desc: 'Remember every client preference — hair color formula, preferred pressure, product sensitivities — for consistently personalized care.' },
      { title: 'Package Tracking', desc: 'Sell multi-session packages and track remaining sessions per client automatically. No spreadsheets needed.' },
      { title: 'Full CRM + Salon Ops', desc: 'Lead capture, email campaigns, and WhatsApp marketing alongside appointment and service management.' },
    ],
    modules: [
      { name: 'Appointment Booking', included: true },
      { name: 'Service Management', included: true },
      { name: 'Staff Management', included: true },
      { name: 'Packages & Combos', included: true },
      { name: 'Product Inventory', included: true },
      { name: 'Client Database', included: true },
      { name: 'Gallery & Portfolio', included: true },
      { name: 'Salon Dashboard', included: true },
      { name: 'WhatsApp & Email Campaigns', included: true },
      { name: 'CMS / Storefront', included: true },
    ],
    recommendedTier: 'Growth',
    testimonial: {
      quote: 'The client profiles remember every detail — hair formulas, preferred stylist, product allergies. Our clients feel genuinely remembered.',
      author: 'Pooja Nair',
      role: 'Founder',
      company: 'Glow Studio Salon',
    },
    faqs: [
      { q: 'Can clients book online?', a: 'Yes. Share a branded booking page on social media or your website. Clients pick a service, stylist, and time slot with instant confirmation.' },
      { q: 'Does it handle walk-ins and appointments?', a: 'Yes. The system handles both scheduled appointments and walk-in customers with queue management.' },
      { q: 'Can I showcase my work?', a: 'Yes. The gallery module lets you upload before/after photos, styling portfolios, and featured transformations — visible to clients.' },
      { q: 'How do packages work?', a: 'Create packages (e.g., "10 haircuts for ₹3000") or combo deals. The system tracks remaining sessions per client with auto-deduction.' },
    ],
    seo: {
      title: 'Salon CRM — Appointments, Services & Client Management | NexCRM',
      description: 'CRM for salons and spas. Manage appointments, track client preferences, sell packages, and showcase your portfolio. Built for Indian beauty businesses.',
      keywords: 'salon CRM India, spa management software, beauty salon CRM, appointment booking salon, salon management system, beauty parlour software, salon marketing tool',
    },
  },
};

export const industryList = Object.entries(industryData).map(([slug, data]) => ({
  slug,
  name: data.name,
  path: `/nexcrm/industries/${slug}`,
  icon: data.icon,
}));
